import React, { useState, useEffect } from 'react'
import { useFirebaseSync } from '../hooks/useFirebaseSync'

/* ─── Types ─────────────────────────────────────────────────── */
export type Property = {
  id: string
  name: string
  address: string
  monthlyRent: number
  deposit: number
  notes: string
}

export type Tenant = {
  id: string
  name: string
  phone: string
  email: string
  extraPhones: string[]
  notes: string
  status: 'lead' | 'active' | 'past'
  interestedPropertyId: string | null
}

export type Tenancy = {
  id: string
  propertyId: string
  tenantId: string
  contractStart: string
  contractEnd: string
  monthlyRent: number
  depositPaid: boolean
  paymentMethod: 'checks' | 'bank' | 'cash' | ''
  checksDelivered: boolean
  contractSigned: boolean
  payments: Record<string, 'paid' | 'pending' | 'late'>
  isCurrent: boolean
}

export type PMTask = {
  id: string
  propertyId: string
  tenantId: string
  tenancyId: string
  type: 'renewal' | 'deposit' | 'checks' | 'custom'
  title: string
  dueDate: string
  done: boolean
  doneAt: string
  autoGenerated: boolean
}

/* ─── Helpers ──────────────────────────────────────────────── */
type Tab = 'properties' | 'tenants' | 'tasks' | 'dashboard'

const todayStr = () => new Date().toISOString().slice(0, 10)
const daysBetween = (a: string, b: string) =>
  Math.round((new Date(b).getTime() - new Date(a).getTime()) / 86400000)
const daysLeft = (end: string) => daysBetween(todayStr(), end)
const fmtMoney = (n: number) => `₪${n.toLocaleString()}`
const monthLabel = (ym: string) => {
  const [y, m] = ym.split('-').map(Number)
  return ['','ינואר','פברואר','מרץ','אפריל','מאי','יוני','יולי','אוגוסט','ספטמבר','אוקטובר','נובמבר','דצמבר'][m] + ' ' + y
}
const currYM = () => {
  const d = new Date()
  return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`
}

/* ─── Component ──────────────────────────────────────────────── */
type Props = { uid: string | null; onBack: () => void }

export function PropertyManagement({ uid, onBack }: Props) {
  const lsKey = (k: string) =>
    uid ? `bva_${uid.slice(0,8)}_pm_${k}` : `bva_local_pm_${k}`

  const [properties, setProperties] = useState<Property[]>(
    () => JSON.parse(localStorage.getItem(lsKey('properties')) || '[]'))
  const [tenants, setTenants] = useState<Tenant[]>(
    () => JSON.parse(localStorage.getItem(lsKey('tenants')) || '[]'))
  const [tenancies, setTenancies] = useState<Tenancy[]>(
    () => JSON.parse(localStorage.getItem(lsKey('tenancies')) || '[]'))
  const [tasks, setTasks] = useState<PMTask[]>(
    () => JSON.parse(localStorage.getItem(lsKey('tasks')) || '[]'))
  const [tab, setTab] = useState<Tab>('properties')
  const [toast, setToast] = useState<string | null>(null)

  const [propView, setPropView] = useState<'list'|'detail'|'editProp'|'editTenancy'|'addTenant'>('list')
  const [selPropId, setSelPropId] = useState<string | null>(null)
  const [selTenancyId, setSelTenancyId] = useState<string | null>(null)
  const [propForm, setPropForm] = useState<Omit<Property,'id'>>({
    name:'', address:'', monthlyRent:0, deposit:0, notes:''
  })
  const [propFormId, setPropFormId] = useState<string | null>(null)
  const [tenancyForm, setTenancyForm] = useState<Omit<Tenancy,'id'|'payments'>>({
    propertyId:'', tenantId:'', contractStart:'', contractEnd:'', monthlyRent:0,
    depositPaid:false, paymentMethod:'', checksDelivered:false, contractSigned:false, isCurrent:true
  })
  const [tenantView, setTenantView] = useState<'list'|'edit'>('list')
  const [tenantForm, setTenantForm] = useState<Omit<Tenant,'id'>>({
    name:'', phone:'', email:'', extraPhones:[], notes:'', status:'lead', interestedPropertyId:null
  })
  const [tenantFormId, setTenantFormId] = useState<string | null>(null)

  useFirebaseSync(uid, 'pm_properties', properties, v => setProperties(v as Property[]))
  useFirebaseSync(uid, 'pm_tenants',    tenants,    v => setTenants(v as Tenant[]))
  useFirebaseSync(uid, 'pm_tenancies',  tenancies,  v => setTenancies(v as Tenancy[]))
  useFirebaseSync(uid, 'pm_tasks',      tasks,      v => setTasks(v as PMTask[]))

  useEffect(() => { localStorage.setItem(lsKey('properties'), JSON.stringify(properties)) }, [properties])
  useEffect(() => { localStorage.setItem(lsKey('tenants'),    JSON.stringify(tenants))    }, [tenants])
  useEffect(() => { localStorage.setItem(lsKey('tenancies'),  JSON.stringify(tenancies))  }, [tenancies])
  useEffect(() => { localStorage.setItem(lsKey('tasks'),      JSON.stringify(tasks))      }, [tasks])

  useEffect(() => {
    const generated: PMTask[] = []
    tenancies.forEach(tn => {
      if (!tn.isCurrent) return
      const days = tn.contractEnd ? daysLeft(tn.contractEnd) : 999
      if (days <= 60 && days >= -30)
        generated.push({ id:`auto_renewal_${tn.id}`, propertyId:tn.propertyId, tenantId:tn.tenantId, tenancyId:tn.id,
          type:'renewal', title:'חידוש חוזה', dueDate:tn.contractEnd, done:false, doneAt:'', autoGenerated:true })
      if (!tn.depositPaid)
        generated.push({ id:`auto_deposit_${tn.id}`, propertyId:tn.propertyId, tenantId:tn.tenantId, tenancyId:tn.id,
          type:'deposit', title:'פיקדון טרם התקבל', dueDate:tn.contractStart||todayStr(), done:false, doneAt:'', autoGenerated:true })
      if (!tn.checksDelivered)
        generated.push({ id:`auto_checks_${tn.id}`, propertyId:tn.propertyId, tenantId:tn.tenantId, tenancyId:tn.id,
          type:'checks', title:"צ'קים / אסמכתה טרם התקבלה", dueDate:tn.contractStart||todayStr(), done:false, doneAt:'', autoGenerated:true })
    })
    setTasks(prev => {
      const manual = prev.filter(t => !t.autoGenerated)
      const merged = generated.map(g => { const ex = prev.find(p => p.id===g.id); return ex ? {...g, done:ex.done, doneAt:ex.doneAt} : g })
      return [...manual, ...merged]
    })
  }, [tenancies])

  const showToast = (msg: string) => { setToast(msg); setTimeout(() => setToast(null), 3000) }
  const sendWA = (phone: string, msg: string) => {
    const clean = phone.replace(/\D/g,'').replace(/^0/,'972')
    window.open(`https://wa.me/${clean}?text=${encodeURIComponent(msg)}`, '_blank')
  }
  const getPropName   = (id: string) => properties.find(p=>p.id===id)?.name || '—'
  const getTenantName = (id: string) => tenants.find(t=>t.id===id)?.name || '—'
  const updateTenancy = (id: string, patch: Partial<Tenancy>) =>
    setTenancies(prev => prev.map(t => t.id===id ? {...t,...patch} : t))

  const selProp        = properties.find(p => p.id===selPropId) ?? null
  const currentTenancy = tenancies.find(t => t.propertyId===selPropId && t.isCurrent) ?? null
  const currentTenant  = currentTenancy ? (tenants.find(t => t.id===currentTenancy.tenantId) ?? null) : null
  const pastTenancies  = tenancies.filter(t => t.propertyId===selPropId && !t.isCurrent)

  const HDR:  React.CSSProperties = { background:'white', borderBottom:'1px solid #E5E7EB', padding:'12px 16px', display:'flex', alignItems:'center', gap:12, position:'sticky', top:0, zIndex:10 }
  const CARD: React.CSSProperties = { background:'white', border:'1px solid #E5E7EB', borderRadius:14, padding:16, marginBottom:12 }
  const INP:  React.CSSProperties = { border:'1.5px solid #E5E7EB', borderRadius:10, padding:'10px 12px', fontSize:15, width:'100%', boxSizing:'border-box' }
  const LBL:  React.CSSProperties = { fontSize:13, color:'#6B7280', fontWeight:600, display:'block', marginBottom:4 }
  const BTN_P: React.CSSProperties = { background:'#6366F1', color:'white', border:'none', borderRadius:10, padding:'8px 16px', fontWeight:700, fontSize:15, cursor:'pointer' }
  const BACK:  React.CSSProperties = { background:'none', border:'none', cursor:'pointer', fontSize:22, color:'#6B7280', padding:'0 4px' }
  const SCROLL: React.CSSProperties = { flex:1, overflowY:'auto', padding:16 }
  /* ════════════════════════════════════════
     TAB 1: Properties — sub-views
  ════════════════════════════════════════ */

  const renderEditProp = () => (
    <div style={{ display:'flex', flexDirection:'column', height:'100dvh', background:'#F9FAFB' }}>
      <div style={HDR}>
        <button style={BACK} onClick={() => setPropView(propFormId ? 'detail' : 'list')}>‹</button>
        <span style={{ fontWeight:700, fontSize:17, flex:1 }}>{propFormId ? 'עריכת נכס' : 'נכס חדש'}</span>
        <button style={BTN_P} onClick={() => {
          if (!propForm.name.trim()) return
          if (propFormId) setProperties(prev => prev.map(p => p.id===propFormId ? {...propForm,id:propFormId} : p))
          else setProperties(prev => [...prev, {...propForm,id:Date.now().toString()}])
          setPropView('list'); showToast('✓ נשמר')
        }}>שמור</button>
      </div>
      <div style={SCROLL}>
        {(['name','address'] as const).map(f => (
          <label key={f} style={{ display:'block', marginBottom:12 }}>
            <span style={LBL}>{f==='name' ? 'שם קצר לנכס' : 'כתובת מלאה'}</span>
            <input style={INP} value={(propForm as any)[f]}
              onChange={e => setPropForm(p=>({...p,[f]:e.target.value}))}
              placeholder={f==='name'?'דירה ת"א':'רחוב הרצל 5'} />
          </label>
        ))}
        <div style={{ display:'grid', gridTemplateColumns:'1fr 1fr', gap:10, marginBottom:12 }}>
          <label>
            <span style={LBL}>שכ"ד חודשי (₪)</span>
            <input style={INP} type="number" value={propForm.monthlyRent||''}
              onChange={e=>setPropForm(p=>({...p,monthlyRent:Number(e.target.value)}))} />
          </label>
          <label>
            <span style={LBL}>פיקדון (₪)</span>
            <input style={INP} type="number" value={propForm.deposit||''}
              onChange={e=>setPropForm(p=>({...p,deposit:Number(e.target.value)}))} />
          </label>
        </div>
        <label style={{ display:'block', marginBottom:12 }}>
          <span style={LBL}>הערות</span>
          <textarea style={{...INP,resize:'none'}} value={propForm.notes}
            onChange={e=>setPropForm(p=>({...p,notes:e.target.value}))} rows={3}/>
        </label>
        {propFormId && (
          <button type="button" onClick={() => {
            setProperties(prev=>prev.filter(p=>p.id!==propFormId))
            setTenancies(prev=>prev.filter(t=>t.propertyId!==propFormId))
            setPropView('list'); showToast('נמחק')
          }} style={{ width:'100%', padding:12, background:'#FEF2F2', border:'1px solid #FECACA', borderRadius:10, color:'#DC2626', fontWeight:600, cursor:'pointer' }}>
            🗑 מחק נכס
          </button>
        )}
      </div>
    </div>
  )

  const renderEditTenancy = () => (
    <div style={{ display:'flex', flexDirection:'column', height:'100dvh', background:'#F9FAFB' }}>
      <div style={HDR}>
        <button style={BACK} onClick={() => setPropView('detail')}>‹</button>
        <span style={{ fontWeight:700, fontSize:17, flex:1 }}>{selTenancyId ? 'עריכת שכירות' : 'קישור שוכר לנכס'}</span>
        <button style={BTN_P} onClick={() => {
          if (!tenancyForm.tenantId || !tenancyForm.contractStart) return
          const id = selTenancyId || `ten_${Date.now()}`
          const existing = selTenancyId ? tenancies.find(t=>t.id===selTenancyId) : null
          const rec: Tenancy = { ...tenancyForm, id, payments: existing?.payments || {} }
          if (selTenancyId) setTenancies(prev => prev.map(t => t.id===selTenancyId ? rec : t))
          else {
            if (tenancyForm.isCurrent)
              setTenancies(prev => prev.map(t => t.propertyId===tenancyForm.propertyId ? {...t,isCurrent:false} : t))
            setTenancies(prev => [...prev, rec])
          }
          setPropView('detail'); showToast('✓ שוכר קושר לנכס')
        }}>שמור</button>
      </div>
      <div style={SCROLL}>
        <label style={{ display:'block', marginBottom:12 }}>
          <span style={LBL}>שוכר</span>
          <select style={INP} value={tenancyForm.tenantId}
            onChange={e=>setTenancyForm(f=>({...f,tenantId:e.target.value}))}>
            <option value="">בחר שוכר...</option>
            {tenants.map(t=><option key={t.id} value={t.id}>{t.name}{t.phone ? ` — ${t.phone}` : ''}</option>)}
          </select>
        </label>
        <div style={{ textAlign:'center', marginBottom:14 }}>
          <button type="button" onClick={() => {
            setTenantForm({name:'',phone:'',email:'',extraPhones:[],notes:'',status:'active',interestedPropertyId:selPropId})
            setTenantFormId(null); setPropView('addTenant')
          }} style={{ background:'#EFF6FF', border:'1px solid #BFDBFE', borderRadius:10, padding:'8px 16px', color:'#1D4ED8', fontWeight:600, cursor:'pointer', fontSize:13 }}>
            + הוסף שוכר חדש
          </button>
        </div>
        <div style={{ display:'grid', gridTemplateColumns:'1fr 1fr', gap:10, marginBottom:12 }}>
          <label>
            <span style={LBL}>תחילת חוזה</span>
            <input style={INP} type="date" value={tenancyForm.contractStart}
              onChange={e=>setTenancyForm(f=>({...f,contractStart:e.target.value}))} />
          </label>
          <label>
            <span style={LBL}>סוף חוזה</span>
            <input style={INP} type="date" value={tenancyForm.contractEnd}
              onChange={e=>setTenancyForm(f=>({...f,contractEnd:e.target.value}))} />
          </label>
        </div>
        <label style={{ display:'block', marginBottom:12 }}>
          <span style={LBL}>שכ"ד חודשי (₪)</span>
          <input style={INP} type="number" value={tenancyForm.monthlyRent||''}
            onChange={e=>setTenancyForm(f=>({...f,monthlyRent:Number(e.target.value)}))} />
        </label>
        <label style={{ display:'block', marginBottom:12 }}>
          <span style={LBL}>אמצעי תשלום</span>
          <select style={INP} value={tenancyForm.paymentMethod}
            onChange={e=>setTenancyForm(f=>({...f,paymentMethod:e.target.value as any}))}>
            <option value="">בחר...</option>
            <option value="checks">המחאות</option>
            <option value="bank">העברה בנקאית</option>
            <option value="cash">מזומן</option>
          </select>
        </label>
        <div style={{ background:'white', borderRadius:12, padding:14, border:'1px solid #E5E7EB', display:'flex', flexDirection:'column', gap:10 }}>
          <div style={{ fontWeight:700, fontSize:13, color:'#374151', marginBottom:4 }}>✅ סטטוס</div>
          {([
            {k:'depositPaid',l:'פיקדון התקבל'},
            {k:'checksDelivered',l:"צ'קים / אסמכתה התקבלה"},
            {k:'contractSigned',l:'חוזה חתום'},
            {k:'isCurrent',l:'שכירות פעילה'},
          ] as const).map(({k,l}) => (
            <label key={k} style={{ display:'flex', alignItems:'center', gap:10, cursor:'pointer' }}>
              <input type="checkbox" checked={(tenancyForm as any)[k]}
                onChange={e=>setTenancyForm(f=>({...f,[k]:e.target.checked}))}
                style={{width:18,height:18}} />
              <span style={{ fontSize:14, fontWeight:500 }}>{l}</span>
            </label>
          ))}
        </div>
      </div>
    </div>
  )
  const renderAddTenantInline = () => (
    <div style={{ display:'flex', flexDirection:'column', height:'100dvh', background:'#F9FAFB' }}>
      <div style={HDR}>
        <button style={BACK} onClick={() => setPropView('editTenancy')}>‹</button>
        <span style={{ fontWeight:700, fontSize:17, flex:1 }}>שוכר חדש</span>
        <button style={BTN_P} onClick={() => {
          if (!tenantForm.name.trim()) return
          const id = Date.now().toString()
          setTenants(prev => [...prev, {...tenantForm, id}])
          setTenancyForm(f => ({...f, tenantId:id}))
          setPropView('editTenancy'); showToast('✓ שוכר נוצר')
        }}>שמור</button>
      </div>
      <div style={SCROLL}>
        {([{f:'name',l:'שם מלא',t:'text'},{f:'phone',l:'טלפון',t:'tel'},{f:'email',l:'דוא"ל',t:'email'}] as const).map(({f,l,t}) => (
          <label key={f} style={{ display:'block', marginBottom:12 }}>
            <span style={LBL}>{l}</span>
            <input style={INP} type={t} value={(tenantForm as any)[f]}
              onChange={e=>setTenantForm(p=>({...p,[f]:e.target.value}))} />
          </label>
        ))}
      </div>
    </div>
  )

  const renderPropDetail = () => {
    if (!selProp) return null
    const p = selProp
    const ct = currentTenancy
    const ctn = currentTenant
    const days = ct?.contractEnd ? daysLeft(ct.contractEnd) : null
    const urgColor = days===null ? '#9CA3AF' : days<0 ? '#EF4444' : days<=60 ? '#F59E0B' : '#22C55E'
    const ym = currYM()
    const pmtStatus = ct?.payments?.[ym]
    return (
      <div style={{ display:'flex', flexDirection:'column', height:'100dvh', background:'#F9FAFB' }}>
        <div style={HDR}>
          <button style={BACK} onClick={() => setPropView('list')}>‹</button>
          <span style={{ fontWeight:700, fontSize:17, flex:1 }}>{p.name || p.address}</span>
          <button type="button" onClick={() => {
            setPropFormId(p.id)
            setPropForm({name:p.name,address:p.address,monthlyRent:p.monthlyRent,deposit:p.deposit,notes:p.notes})
            setPropView('editProp')
          }} style={{ background:'#F3F4F6', border:'none', borderRadius:8, padding:'6px 14px', fontWeight:600, cursor:'pointer', color:'#374151' }}>ערוך</button>
        </div>
        <div style={SCROLL}>
          {/* Basic info */}
          <div style={CARD}>
            <div style={{ fontSize:13, color:'#6B7280' }}>📍 {p.address}</div>
            <div style={{ display:'flex', gap:12, marginTop:8, flexWrap:'wrap', alignItems:'center' }}>
              <span style={{ fontWeight:700, fontSize:16 }}>{fmtMoney(p.monthlyRent)}/חודש</span>
              {p.deposit>0 && <span style={{ fontSize:13, color:'#6B7280' }}>פיקדון: {fmtMoney(p.deposit)}</span>}
            </div>
            {p.notes && <div style={{ marginTop:8, fontSize:13, color:'#92400E', background:'#FFF7ED', borderRadius:8, padding:'6px 10px' }}>📝 {p.notes}</div>}
          </div>

          {/* Current tenant */}
          <div style={CARD}>
            <div style={{ display:'flex', justifyContent:'space-between', alignItems:'center', marginBottom:12 }}>
              <div style={{ fontWeight:700, fontSize:14 }}>👤 שוכר נוכחי</div>
              <button type="button" onClick={() => {
                setSelTenancyId(null)
                setTenancyForm({propertyId:p.id,tenantId:'',contractStart:'',contractEnd:'',monthlyRent:p.monthlyRent,depositPaid:false,paymentMethod:'',checksDelivered:false,contractSigned:false,isCurrent:true})
                setPropView('editTenancy')
              }} style={{ background:'#EFF6FF', border:'1px solid #BFDBFE', borderRadius:8, padding:'5px 12px', color:'#1D4ED8', fontWeight:600, cursor:'pointer', fontSize:12 }}>
                {ct ? 'החלף / ערוך' : '+ קשר שוכר'}
              </button>
            </div>
            {ct && ctn ? (
              <>
                <div style={{ fontWeight:700, fontSize:16, marginBottom:4 }}>{ctn.name}</div>
                {ctn.phone && <div style={{ fontSize:13, color:'#6B7280', marginBottom:2 }}>📞 {ctn.phone}</div>}
                {ctn.email && <div style={{ fontSize:13, color:'#6B7280', marginBottom:8 }}>✉ {ctn.email}</div>}
                <div style={{ display:'flex', alignItems:'center', gap:8, marginBottom:12 }}>
                  <span style={{ fontSize:12, background:urgColor+'20', color:urgColor, borderRadius:20, padding:'2px 10px', fontWeight:700 }}>
                    {days===null ? '—' : days<0 ? 'פג תוקף' : `${days} ימים`}
                  </span>
                  <span style={{ fontSize:12, color:'#6B7280' }}>{ct.contractStart} → {ct.contractEnd}</span>
                </div>
                {/* Checklist */}
                <div style={{ background:'#F9FAFB', borderRadius:10, padding:12, marginBottom:12, display:'flex', flexDirection:'column', gap:8 }}>
                  {([
                    {k:'depositPaid', l:'פיקדון התקבל'},
                    {k:'checksDelivered', l:"צ'קים / אסמכתה"},
                    {k:'contractSigned', l:'חוזה חתום'},
                  ] as const).map(({k,l}) => {
                    const val = (ct as any)[k] as boolean
                    return (
                      <button key={k} type="button" onClick={() => updateTenancy(ct.id, {[k]:!val} as any)}
                        style={{ display:'flex', alignItems:'center', gap:10, background:val?'#F0FDF4':'white', border:val?'1px solid #BBF7D0':'1px solid #E5E7EB', borderRadius:8, padding:'8px 12px', cursor:'pointer', textAlign:'right' }}>
                        <span style={{ fontSize:18, color:val?'#16A34A':'#9CA3AF' }}>{val?'✅':'☐'}</span>
                        <span style={{ fontSize:13, fontWeight:600, color:val?'#15803D':'#374151' }}>{l}</span>
                      </button>
                    )
                  })}
                </div>
                {/* Quick action buttons */}
                <div style={{ display:'grid', gridTemplateColumns:'1fr 1fr', gap:8, marginBottom:14 }}>
                  {[
                    {label:'🔄 חידוש חוזה', bg:'#F0FDF4', bc:'#BBF7D0', c:'#15803D',
                      msg:`שלום ${ctn.name}, תזכורת לחידוש חוזה השכירות עבור ${p.name}. החוזה מסתיים ב-${ct.contractEnd}. האם ברצונך לחדש? 🙏`},
                    {label:'💰 תזכורת פיקדון', bg:'#EFF6FF', bc:'#BFDBFE', c:'#1D4ED8',
                      msg:`שלום ${ctn.name}, תזכורת להעברת פיקדון (${fmtMoney(p.deposit)}) עבור ${p.name}. תודה 🙏`},
                    {label:"📑 תזכורת צ'קים", bg:'#FFF7ED', bc:'#FED7AA', c:'#C2410C',
                      msg:`שלום ${ctn.name}, תזכורת לשלוח צ'קים / אסמכתה עבור ${p.name}. תודה 🙏`},
                    {label:'💬 תזכורת תשלום', bg:'#F5F3FF', bc:'#DDD6FE', c:'#7C3AED',
                      msg:`שלום ${ctn.name}, תזכורת לתשלום שכ"ד חודש ${monthLabel(ym)} עבור ${p.name}: ${fmtMoney(ct.monthlyRent||p.monthlyRent)}. תודה 🙏`},
                  ].map(({label,bg,bc,c,msg}) => (
                    <button key={label} type="button"
                      onClick={() => ctn.phone ? sendWA(ctn.phone, msg) : alert('אין טלפון רשום')}
                      style={{ padding:'10px 8px', background:bg, border:`1px solid ${bc}`, borderRadius:10, color:c, fontWeight:700, cursor:'pointer', fontSize:12 }}>
                      {label}
                    </button>
                  ))}
                </div>
                {/* Monthly payment tracker */}
                <div style={{ borderTop:'1px solid #F3F4F6', paddingTop:12 }}>
                  <div style={{ fontWeight:700, fontSize:13, marginBottom:8 }}>💳 תשלום חודשי — {monthLabel(ym)}</div>
                  <div style={{ background:'#EFF6FF', borderRadius:10, padding:'10px 12px', border:'1px solid #BFDBFE', display:'flex', alignItems:'center', gap:8, flexWrap:'wrap' }}>
                    {(['paid','pending','late'] as const).map(s => (
                      <button key={s} type="button" onClick={() => updateTenancy(ct.id, {payments:{...ct.payments,[ym]:s}})}
                        style={{ flex:1, padding:'8px 6px', borderRadius:8, border:'none', cursor:'pointer', fontSize:12, fontWeight:700,
                          background:pmtStatus===s ? (s==='paid'?'#22C55E':s==='late'?'#EF4444':'#F59E0B') : '#E5E7EB',
                          color:pmtStatus===s ? 'white' : '#6B7280' }}>
                        {s==='paid' ? '✓ שולם' : s==='late' ? '⚠ מאחר' : '⏳ ממתין'}
                      </button>
                    ))}
                  </div>
                </div>
              </>
            ) : (
              <div style={{ textAlign:'center', padding:'20px', color:'#9CA3AF', fontSize:14 }}>אין שוכר פעיל</div>
            )}
          </div>

          {/* Past tenants */}
          {pastTenancies.length > 0 && (
            <div style={CARD}>
              <div style={{ fontWeight:700, fontSize:14, marginBottom:10 }}>📜 שוכרים לשעבר</div>
              {pastTenancies.map(pt => (
                <div key={pt.id} style={{ display:'flex', justifyContent:'space-between', alignItems:'center', padding:'8px 0', borderBottom:'1px solid #F3F4F6' }}>
                  <span style={{ fontWeight:600, fontSize:14 }}>{getTenantName(pt.tenantId)}</span>
                  <span style={{ fontSize:12, color:'#9CA3AF' }}>{pt.contractStart} → {pt.contractEnd}</span>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>
    )
  }
  const renderPropList = () => (
    <>
      <div style={HDR}>
        <button style={BACK} onClick={onBack}>‹</button>
        <span style={{ fontWeight:700, fontSize:17, flex:1 }}>🏠 נכסים</span>
        <button style={BTN_P} onClick={() => {
          setPropFormId(null); setPropForm({name:'',address:'',monthlyRent:0,deposit:0,notes:''}); setPropView('editProp')
        }}>+ נכס</button>
      </div>
      <div style={SCROLL}>
        {properties.length===0 ? (
          <div style={{ textAlign:'center', padding:'60px 20px', color:'#9CA3AF' }}>
            <div style={{ fontSize:48, marginBottom:12 }}>🏠</div>
            <div style={{ fontWeight:700, fontSize:16, color:'#374151', marginBottom:6 }}>אין נכסים עדיין</div>
            <div style={{ fontSize:14 }}>לחץ "+ נכס" להתחלה</div>
          </div>
        ) : properties.map(p => {
          const ct = tenancies.find(t=>t.propertyId===p.id&&t.isCurrent)
          const ctn = ct ? tenants.find(t=>t.id===ct.tenantId) : null
          const days = ct?.contractEnd ? daysLeft(ct.contractEnd) : null
          const urg = days===null ? '#9CA3AF' : days<0 ? '#EF4444' : days<=60 ? '#F59E0B' : '#22C55E'
          return (
            <button key={p.id} type="button" onClick={() => { setSelPropId(p.id); setPropView('detail') }}
              style={{ ...CARD, width:'100%', textAlign:'right', cursor:'pointer', display:'flex', flexDirection:'column', gap:8 }}>
              <div style={{ display:'flex', justifyContent:'space-between', alignItems:'flex-start' }}>
                <div style={{ flex:1 }}>
                  <div style={{ fontWeight:700, fontSize:16, color:'#111827' }}>{p.name || p.address}</div>
                  <div style={{ fontSize:12, color:'#6B7280' }}>{p.address}</div>
                </div>
                {days!==null && (
                  <span style={{ fontSize:11, background:urg+'20', color:urg, borderRadius:20, padding:'2px 8px', fontWeight:700, marginRight:8, whiteSpace:'nowrap' }}>
                    {days<0 ? 'פג תוקף' : `${days}י'`}
                  </span>
                )}
              </div>
              <div style={{ display:'flex', justifyContent:'space-between', alignItems:'center' }}>
                <span style={{ fontWeight:700, fontSize:15, color:'#111827' }}>{fmtMoney(p.monthlyRent)}/חודש</span>
                <span style={{ fontSize:13, color:ctn?'#374151':'#9CA3AF' }}>{ctn ? ctn.name : 'פנוי'}</span>
              </div>
            </button>
          )
        })}
      </div>
      {properties.length>0 && (
        <div style={{ background:'white', borderTop:'1px solid #E5E7EB', padding:'12px 20px', display:'flex', justifyContent:'space-around', flexShrink:0 }}>
          <div style={{ textAlign:'center' }}><div style={{ fontSize:18, fontWeight:700 }}>{properties.length}</div><div style={{ fontSize:11, color:'#6B7280' }}>נכסים</div></div>
          <div style={{ textAlign:'center' }}><div style={{ fontSize:18, fontWeight:700, color:'#22C55E' }}>{fmtMoney(properties.reduce((s,p)=>s+p.monthlyRent,0))}</div><div style={{ fontSize:11, color:'#6B7280' }}>שכ"ד חודשי</div></div>
          <div style={{ textAlign:'center' }}><div style={{ fontSize:18, fontWeight:700, color:'#6366F1' }}>{tenancies.filter(t=>t.isCurrent).length}</div><div style={{ fontSize:11, color:'#6B7280' }}>מושכרים</div></div>
        </div>
      )}
    </>
  )

  const renderPropertiesTab = () => {
    if (propView==='editProp')    return renderEditProp()
    if (propView==='editTenancy') return renderEditTenancy()
    if (propView==='addTenant')   return renderAddTenantInline()
    if (propView==='detail')      return renderPropDetail()
    return null
  }

  /* ════════════════════════════════════════
     TAB 2 — TENANTS
  ════════════════════════════════════════ */
  const renderTenantsTab = () => {
    if (tenantView==='edit') return (
      <div style={{ display:'flex', flexDirection:'column', height:'100dvh', background:'#F9FAFB' }}>
        <div style={HDR}>
          <button style={BACK} onClick={() => setTenantView('list')}>‹</button>
          <span style={{ fontWeight:700, fontSize:17, flex:1 }}>{tenantFormId ? 'עריכת שוכר' : 'שוכר חדש'}</span>
          <button style={BTN_P} onClick={() => {
            if (!tenantForm.name.trim()) return
            if (tenantFormId) setTenants(prev=>prev.map(t=>t.id===tenantFormId?{...tenantForm,id:tenantFormId}:t))
            else setTenants(prev=>[...prev,{...tenantForm,id:Date.now().toString()}])
            setTenantView('list'); showToast('✓ נשמר')
          }}>שמור</button>
        </div>
        <div style={SCROLL}>
          {([{f:'name',l:'שם מלא',t:'text'},{f:'phone',l:'טלפון',t:'tel'},{f:'email',l:'דוא"ל',t:'email'}] as const).map(({f,l,t}) => (
            <label key={f} style={{ display:'block', marginBottom:12 }}>
              <span style={LBL}>{l}</span>
              <input style={INP} type={t} value={(tenantForm as any)[f]} onChange={e=>setTenantForm(p=>({...p,[f]:e.target.value}))} />
            </label>
          ))}
          <label style={{ display:'block', marginBottom:12 }}>
            <span style={LBL}>סטטוס</span>
            <select style={INP} value={tenantForm.status} onChange={e=>setTenantForm(p=>({...p,status:e.target.value as any}))}>
              <option value="lead">מתעניין / ליד</option>
              <option value="active">שוכר פעיל</option>
              <option value="past">שוכר לשעבר</option>
            </select>
          </label>
          {tenantForm.status==='lead' && (
            <label style={{ display:'block', marginBottom:12 }}>
              <span style={LBL}>מתעניין בנכס</span>
              <select style={INP} value={tenantForm.interestedPropertyId||''} onChange={e=>setTenantForm(p=>({...p,interestedPropertyId:e.target.value||null}))}>
                <option value="">בחר נכס...</option>
                {properties.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}
              </select>
            </label>
          )}
          <label style={{ display:'block', marginBottom:12 }}>
            <span style={LBL}>הערות</span>
            <textarea style={{...INP,resize:'none'}} value={tenantForm.notes} onChange={e=>setTenantForm(p=>({...p,notes:e.target.value}))} rows={3}/>
          </label>
          {tenantFormId && (
            <button type="button" onClick={()=>{setTenants(p=>p.filter(t=>t.id!==tenantFormId));setTenantView('list');showToast('נמחק')}}
              style={{ width:'100%', padding:12, background:'#FEF2F2', border:'1px solid #FECACA', borderRadius:10, color:'#DC2626', fontWeight:600, cursor:'pointer' }}>
              🗑 מחק שוכר
            </button>
          )}
        </div>
      </div>
    )

    const STATUS_LABELS: Record<Tenant['status'],string> = { lead:'מתעניינים', active:'שוכרים פעילים', past:'לשעבר' }
    const STATUS_COLORS: Record<Tenant['status'],string> = { lead:'#F59E0B', active:'#22C55E', past:'#9CA3AF' }
    return (
      <>
        <div style={HDR}>
          <span style={{ fontWeight:700, fontSize:17, flex:1 }}>👤 שוכרים</span>
          <button style={BTN_P} onClick={() => {
            setTenantFormId(null); setTenantForm({name:'',phone:'',email:'',extraPhones:[],notes:'',status:'lead',interestedPropertyId:null}); setTenantView('edit')
          }}>+ שוכר</button>
        </div>
        <div style={SCROLL}>
          {tenants.length===0 ? (
            <div style={{ textAlign:'center', padding:'60px 20px', color:'#9CA3AF' }}>
              <div style={{ fontSize:48, marginBottom:12 }}>👤</div>
              <div style={{ fontWeight:700, fontSize:16, color:'#374151' }}>אין שוכרים עדיין</div>
            </div>
          ) : (['lead','active','past'] as Tenant['status'][]).map(status => {
            const group = tenants.filter(t=>t.status===status)
            if (group.length===0) return null
            return (
              <div key={status} style={{ marginBottom:16 }}>
                <div style={{ fontSize:12, fontWeight:700, color:STATUS_COLORS[status], marginBottom:8, padding:'0 4px' }}>
                  {STATUS_LABELS[status]} ({group.length})
                </div>
                {group.map(t => {
                  const intProp = t.interestedPropertyId ? properties.find(p=>p.id===t.interestedPropertyId) : null
                  const activeTn = tenancies.find(tn=>tn.tenantId===t.id&&tn.isCurrent)
                  const activeProp = activeTn ? properties.find(p=>p.id===activeTn.propertyId) : null
                  return (
                    <div key={t.id} style={CARD}>
                      <div style={{ display:'flex', justifyContent:'space-between', alignItems:'flex-start', marginBottom:6 }}>
                        <div style={{ flex:1 }}>
                          <div style={{ fontWeight:700, fontSize:15, color:'#111827' }}>{t.name}</div>
                          {t.phone && <div style={{ fontSize:13, color:'#6B7280' }}>📞 {t.phone}</div>}
                          {t.email && <div style={{ fontSize:13, color:'#6B7280' }}>✉ {t.email}</div>}
                          {intProp && <div style={{ fontSize:12, color:'#F59E0B', fontWeight:600, marginTop:4 }}>🔍 מתעניין ב: {intProp.name}</div>}
                          {activeProp && <div style={{ fontSize:12, color:'#22C55E', fontWeight:600, marginTop:4 }}>🏠 שוכר ב: {activeProp.name} עד {activeTn?.contractEnd}</div>}
                          {t.notes && <div style={{ fontSize:12, color:'#9CA3AF', marginTop:4 }}>📝 {t.notes}</div>}
                        </div>
                        <button type="button" onClick={() => { setTenantFormId(t.id); setTenantForm({name:t.name,phone:t.phone,email:t.email,extraPhones:t.extraPhones,notes:t.notes,status:t.status,interestedPropertyId:t.interestedPropertyId}); setTenantView('edit') }}
                          style={{ background:'#F3F4F6', border:'none', borderRadius:8, padding:'4px 10px', fontWeight:600, cursor:'pointer', fontSize:12, color:'#374151', flexShrink:0, marginRight:8 }}>ערוך</button>
                      </div>
                      {t.phone && (
                        <div style={{ display:'flex', gap:8, marginTop:8 }}>
                          <button type="button" onClick={()=>sendWA(t.phone,`שלום ${t.name}, `)} style={{ flex:1, padding:'7px', background:'#F0FDF4', border:'1px solid #BBF7D0', borderRadius:8, color:'#15803D', fontWeight:600, cursor:'pointer', fontSize:12 }}>💬 WhatsApp</button>
                          <button type="button" onClick={()=>{window.location.href=`tel:${t.phone}`}} style={{ flex:1, padding:'7px', background:'#F9FAFB', border:'1px solid #E5E7EB', borderRadius:8, color:'#374151', fontWeight:600, cursor:'pointer', fontSize:12 }}>📞 התקשר</button>
                          {t.email && <button type="button" onClick={()=>{window.location.href=`mailto:${t.email}`}} style={{ flex:1, padding:'7px', background:'#EFF6FF', border:'1px solid #BFDBFE', borderRadius:8, color:'#1D4ED8', fontWeight:600, cursor:'pointer', fontSize:12 }}>✉ מייל</button>}
                        </div>
                      )}
                    </div>
                  )
                })}
              </div>
            )
          })}
        </div>
      </>
    )
  }
  /* ════════════════════════════════════════
     TAB 3 — TASKS
  ════════════════════════════════════════ */
  const renderTasksTab = () => {
    const open = tasks.filter(t=>!t.done)
    const done = tasks.filter(t=>t.done)
    const urgency = (t: PMTask) => {
      const d = daysBetween(todayStr(), t.dueDate)
      if (d<=7) return 0; if (d<=30) return 1; return 2
    }
    const ICONS: Record<string,string> = { renewal:'🔄', deposit:'💰', checks:'📑', custom:'📌' }
    const GROUPS = [
      { label:'🔴 דחוף — השבוע',   filter:(t:PMTask)=>urgency(t)===0 },
      { label:'🟠 בקרוב — החודש', filter:(t:PMTask)=>urgency(t)===1 },
      { label:'🟡 בהמשך',         filter:(t:PMTask)=>urgency(t)===2 },
    ]
    return (
      <>
        <div style={HDR}>
          <span style={{ fontWeight:700, fontSize:17, flex:1 }}>✅ משימות</span>
          {open.length>0 && <span style={{ background:'#EF4444', color:'white', borderRadius:20, padding:'2px 10px', fontSize:12, fontWeight:700, marginLeft:4 }}>{open.length}</span>}
          <button style={BTN_P} onClick={() => {
            const title = prompt('כותרת המשימה')
            if (!title) return
            setTasks(prev=>[...prev,{id:Date.now().toString(),propertyId:'',tenantId:'',tenancyId:'',type:'custom',title,dueDate:todayStr(),done:false,doneAt:'',autoGenerated:false}])
          }}>+ משימה</button>
        </div>
        <div style={SCROLL}>
          {open.length===0 && (
            <div style={{ textAlign:'center', padding:'60px 20px', color:'#9CA3AF' }}>
              <div style={{ fontSize:48 }}>✅</div>
              <div style={{ fontWeight:700, fontSize:16, color:'#374151', marginTop:12 }}>אין משימות פתוחות</div>
            </div>
          )}
          {GROUPS.map(g => {
            const group = open.filter(g.filter)
            if (group.length===0) return null
            return (
              <div key={g.label} style={{ marginBottom:16 }}>
                <div style={{ fontSize:13, fontWeight:700, color:'#374151', marginBottom:8 }}>{g.label}</div>
                {group.map(t => {
                  const tn = t.tenantId ? tenants.find(x=>x.id===t.tenantId) : null
                  return (
                    <div key={t.id} style={{ ...CARD, display:'flex', alignItems:'flex-start', gap:10, padding:'12px 14px' }}>
                      <button type="button" onClick={() => setTasks(prev=>prev.map(x=>x.id===t.id?{...x,done:true,doneAt:todayStr()}:x))}
                        style={{ width:24, height:24, borderRadius:'50%', border:'2px solid #D1D5DB', background:'white', cursor:'pointer', flexShrink:0, marginTop:2, fontSize:13, display:'flex', alignItems:'center', justifyContent:'center' }}>☐</button>
                      <div style={{ flex:1 }}>
                        <div style={{ fontWeight:700, fontSize:14 }}>{ICONS[t.type]} {t.title}</div>
                        {t.propertyId && <div style={{ fontSize:12, color:'#6B7280', marginTop:2 }}>🏠 {getPropName(t.propertyId)}{t.tenantId ? ` — ${getTenantName(t.tenantId)}` : ''}</div>}
                        <div style={{ fontSize:11, color:'#9CA3AF', marginTop:2 }}>עד: {t.dueDate}</div>
                      </div>
                      {tn?.phone && (
                        <button type="button" onClick={() => {
                          const msgs: Record<string,string> = {
                            renewal:`שלום ${tn.name}, תזכורת לחידוש חוזה עבור ${getPropName(t.propertyId)}. 🙏`,
                            deposit:`שלום ${tn.name}, תזכורת להעברת פיקדון עבור ${getPropName(t.propertyId)}. 🙏`,
                            checks:`שלום ${tn.name}, תזכורת לשלוח צ'קים עבור ${getPropName(t.propertyId)}. 🙏`,
                            custom:`שלום ${tn.name}, ${t.title}`,
                          }
                          sendWA(tn.phone, msgs[t.type] || msgs.custom)
                        }} style={{ padding:'6px 10px', background:'#F0FDF4', border:'1px solid #BBF7D0', borderRadius:8, color:'#15803D', fontWeight:600, cursor:'pointer', fontSize:11, flexShrink:0 }}>שלח</button>
                      )}
                    </div>
                  )
                })}
              </div>
            )
          })}
          {done.length>0 && (
            <div style={{ marginBottom:16 }}>
              <div style={{ fontSize:13, fontWeight:700, color:'#9CA3AF', marginBottom:8 }}>✅ הושלמו ({done.length})</div>
              {done.slice(0,5).map(t => (
                <div key={t.id} style={{ ...CARD, display:'flex', alignItems:'center', gap:10, padding:'10px 14px', opacity:0.6 }}>
                  <span style={{ fontSize:18 }}>✅</span>
                  <div style={{ flex:1 }}>
                    <div style={{ fontWeight:600, fontSize:13, textDecoration:'line-through' }}>{t.title}</div>
                    <div style={{ fontSize:11, color:'#9CA3AF' }}>{getPropName(t.propertyId)}</div>
                  </div>
                  <button type="button" onClick={()=>setTasks(prev=>prev.map(x=>x.id===t.id?{...x,done:false,doneAt:''}:x))}
                    style={{ background:'none', border:'1px solid #E5E7EB', borderRadius:8, padding:'4px 8px', cursor:'pointer', fontSize:11, color:'#6B7280' }}>בטל</button>
                </div>
              ))}
            </div>
          )}
        </div>
      </>
    )
  }

  /* ════════════════════════════════════════
     TAB 4 — DASHBOARD
  ════════════════════════════════════════ */
  const renderDashboard = () => {
    const totalMonthly = properties.reduce((s,p)=>s+p.monthlyRent,0)
    const rented = tenancies.filter(t=>t.isCurrent)
    const vacant = properties.filter(p=>!rented.find(t=>t.propertyId===p.id))
    const ganttMonths: string[] = []
    const now = new Date()
    for (let i=-2; i<10; i++) {
      const d = new Date(now.getFullYear(), now.getMonth()+i, 1)
      ganttMonths.push(`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`)
    }
    const cm = currYM()
    return (
      <>
        <div style={HDR}>
          <span style={{ fontWeight:700, fontSize:17, flex:1 }}>📊 דשבורד</span>
        </div>
        <div style={SCROLL}>
          {/* KPI cards */}
          <div style={{ display:'grid', gridTemplateColumns:'1fr 1fr 1fr', gap:10, marginBottom:16 }}>
            {[
              { label:'שכ"ד חודשי', val:fmtMoney(totalMonthly), color:'#22C55E' },
              { label:'שכ"ד שנתי',  val:fmtMoney(totalMonthly*12), color:'#6366F1' },
              { label:'נכסים פנויים', val:String(vacant.length), color:vacant.length>0?'#EF4444':'#22C55E' },
            ].map(({label,val,color}) => (
              <div key={label} style={{ background:'white', borderRadius:12, padding:'12px 10px', border:'1px solid #E5E7EB', textAlign:'center' }}>
                <div style={{ fontSize:16, fontWeight:700, color }}>{val}</div>
                <div style={{ fontSize:10, color:'#9CA3AF', marginTop:2 }}>{label}</div>
              </div>
            ))}
          </div>

          {/* Per-property income */}
          <div style={CARD}>
            <div style={{ fontWeight:700, fontSize:14, marginBottom:12 }}>💰 הכנסות לפי נכס</div>
            {properties.map(p => {
              const ct = rented.find(t=>t.propertyId===p.id)
              const ctn = ct ? tenants.find(t=>t.id===ct.tenantId) : null
              const days = ct?.contractEnd ? daysLeft(ct.contractEnd) : null
              const dc = days===null?'#9CA3AF':days<0?'#EF4444':days<=60?'#F59E0B':'#22C55E'
              return (
                <div key={p.id} style={{ display:'flex', justifyContent:'space-between', alignItems:'center', padding:'10px 0', borderBottom:'1px solid #F3F4F6' }}>
                  <div>
                    <div style={{ fontWeight:600, fontSize:14 }}>{p.name}</div>
                    <div style={{ fontSize:12, color:ctn?'#6B7280':'#EF4444' }}>{ctn ? ctn.name : 'פנוי'}</div>
                  </div>
                  <div style={{ textAlign:'left' }}>
                    <div style={{ fontWeight:700, fontSize:15, color:ctn?'#22C55E':'#EF4444' }}>{ctn ? fmtMoney(p.monthlyRent) : '₪0'}</div>
                    {days!==null && <div style={{ fontSize:11, color:dc }}>{days<0?'פג תוקף':`${days}י' לסיום`}</div>}
                  </div>
                </div>
              )
            })}
          </div>

          {/* Gantt */}
          <div style={CARD}>
            <div style={{ fontWeight:700, fontSize:14, marginBottom:12 }}>📅 לוח זמינות נכסים</div>
            <div style={{ overflowX:'auto' }}>
              <table style={{ borderCollapse:'collapse', minWidth:'100%', fontSize:11 }}>
                <thead>
                  <tr>
                    <th style={{ textAlign:'right', padding:'4px 8px', color:'#6B7280', minWidth:70 }}>נכס</th>
                    {ganttMonths.map(m => (
                      <th key={m} style={{ padding:'4px 3px', color:m===cm?'#6366F1':'#9CA3AF', fontWeight:m===cm?700:400, minWidth:34, textAlign:'center', borderRight:'1px solid #F3F4F6' }}>
                        {m.slice(5)}
                      </th>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  {properties.map(p => {
                    const propTen = tenancies.filter(t=>t.propertyId===p.id)
                    return (
                      <tr key={p.id} style={{ borderTop:'1px solid #F3F4F6' }}>
                        <td style={{ padding:'6px 8px', fontWeight:600, color:'#374151', fontSize:12 }}>{p.name}</td>
                        {ganttMonths.map(m => {
                          const tn = propTen.find(t => t.contractStart.slice(0,7)<=m && t.contractEnd.slice(0,7)>=m)
                          const bg = tn ? (tn.isCurrent ? '#22C55E' : '#A78BFA') : '#FEE2E2'
                          const isEnd = tn && tn.contractEnd.slice(0,7)===m
                          return (
                            <td key={m} style={{ padding:'6px 3px', background:bg, textAlign:'center', borderRight:'1px solid #F9FAFB', fontSize:9, color:'white', fontWeight:700 }}>
                              {isEnd ? '⚠' : ''}
                            </td>
                          )
                        })}
                      </tr>
                    )
                  })}
                </tbody>
              </table>
              <div style={{ display:'flex', gap:12, marginTop:8, fontSize:11, color:'#6B7280', flexWrap:'wrap' }}>
                <span><span style={{ display:'inline-block', width:12, height:10, background:'#22C55E', borderRadius:2, marginLeft:4 }}/>מושכר פעיל</span>
                <span><span style={{ display:'inline-block', width:12, height:10, background:'#A78BFA', borderRadius:2, marginLeft:4 }}/>מושכר בעבר</span>
                <span><span style={{ display:'inline-block', width:12, height:10, background:'#FEE2E2', border:'1px solid #FECACA', borderRadius:2, marginLeft:4 }}/>פנוי</span>
              </div>
            </div>
          </div>
        </div>
      </>
    )
  }

  /* ════════════════════════════════════════
     MAIN RENDER
  ════════════════════════════════════════ */
  const TABS = [
    { id:'properties' as Tab, label:'נכסים',  icon:'🏠' },
    { id:'tenants'    as Tab, label:'שוכרים', icon:'👤' },
    { id:'tasks'      as Tab, label:'משימות', icon:'✅' },
    { id:'dashboard'  as Tab, label:'דשבורד', icon:'📊' },
  ]
  const openTaskCount = tasks.filter(t=>!t.done).length

  // Full-screen sub-views that take over the whole screen (no tab bar)
  const isFullScreen =
    (tab==='properties' && ['detail','editProp','editTenancy','addTenant'].includes(propView)) ||
    (tab==='tenants' && tenantView==='edit')

  const subView = isFullScreen ? (
    tab==='properties' ? renderPropertiesTab() : renderTenantsTab()
  ) : null

  if (isFullScreen) return (
    <>
      {subView}
      {toast && (
        <div style={{ position:'fixed', bottom:20, left:'50%', transform:'translateX(-50%)', background:'#1F2937', color:'white', padding:'10px 20px', borderRadius:20, fontWeight:600, zIndex:200, whiteSpace:'nowrap' }}>
          {toast}
        </div>
      )}
    </>
  )

  return (
    <div style={{ display:'flex', flexDirection:'column', height:'100dvh', background:'#F9FAFB' }}>
      <div style={{ flex:1, overflowY:'auto', display:'flex', flexDirection:'column', minHeight:0 }}>
        {tab==='properties' && renderPropList()}
        {tab==='tenants'    && renderTenantsTab()}
        {tab==='tasks'      && renderTasksTab()}
        {tab==='dashboard'  && renderDashboard()}
      </div>

      {/* Tab bar */}
      <div style={{ background:'white', borderTop:'1px solid #E5E7EB', display:'flex', flexShrink:0 }}>
        {TABS.map(({id,label,icon}) => (
          <button key={id} type="button"
            onClick={() => { setTab(id); if(id==='properties') setPropView('list'); if(id==='tenants') setTenantView('list') }}
            style={{ flex:1, padding:'10px 4px 12px', background:'none', border:'none', cursor:'pointer',
              display:'flex', flexDirection:'column', alignItems:'center', gap:3,
              color:tab===id ? '#6366F1' : '#9CA3AF',
              fontWeight:tab===id ? 700 : 500, fontSize:10,
              borderTop:tab===id ? '2px solid #6366F1' : '2px solid transparent',
              position:'relative' }}>
            <span style={{ fontSize:18 }}>{icon}</span>
            <span>{label}</span>
            {id==='tasks' && openTaskCount>0 && (
              <span style={{ position:'absolute', top:4, right:'18%', background:'#EF4444', color:'white', borderRadius:10, padding:'1px 5px', fontSize:9, fontWeight:700 }}>
                {openTaskCount}
              </span>
            )}
          </button>
        ))}
      </div>

      {toast && (
        <div style={{ position:'fixed', bottom:80, left:'50%', transform:'translateX(-50%)', background:'#1F2937', color:'white', padding:'10px 20px', borderRadius:20, fontWeight:600, zIndex:200, whiteSpace:'nowrap' }}>
          {toast}
        </div>
      )}
    </div>
  )
}
