import React, { useState, useEffect, useRef } from 'react'
import { useFirebaseSync } from '../hooks/useFirebaseSync'
import { tt, type Lang } from '../i18n/timeTracking'

/* ─── Types ─────────────────────────────────────────────────── */
export type Property = {
  id: string
  name: string
  address: string
  monthlyRent: number
  deposit: number
  notes: string
}

export type Tenant = {
  id: string
  name: string
  phone: string
  email: string
  extraPhones: string[]
  notes: string
  status: 'lead' | 'active' | 'past'
  interestedPropertyId: string | null
}

export type Tenancy = {
  id: string
  propertyId: string
  tenantId: string
  contractStart: string
  contractEnd: string
  monthlyRent: number
  deposit?: number
  renewalRent?: number
  depositPaid: boolean
  paymentMethod: 'checks' | 'bank' | 'cash' | ''
  checksDelivered: boolean
  contractSigned: boolean
  payments: Record<string, 'paid' | 'pending' | 'late'>
  isCurrent: boolean
  hasOption?: boolean
}

export type TenancyDoc = {
  id: string
  tenancyId: string
  propertyId: string
  name: string
  type: 'contract' | 'renewal' | 'receipt' | 'other'
  date: string
  mimeType: string
  size: number
  // binary data stored separately in localStorage under key pm_doc_data_{id}
}

export type PMTask = {
  id: string
  propertyId: string
  tenantId: string
  tenancyId: string
  type: 'renewal' | 'deposit' | 'checks' | 'custom'
  title: string
  dueDate: string
  done: boolean
  doneAt: string
  autoGenerated: boolean
}

/* ─── Helpers ──────────────────────────────────────────────── */
type Tab = 'properties' | 'tenants' | 'tasks' | 'dashboard'

const todayStr = () => new Date().toISOString().slice(0, 10)
const daysBetween = (a: string, b: string) =>
  Math.round((new Date(b).getTime() - new Date(a).getTime()) / 86400000)
const daysLeft = (end: string) => daysBetween(todayStr(), end)
const fmtMoney = (n: number) => `₪${n.toLocaleString()}`
const monthLabel = (ym: string) => {
  const [y, m] = ym.split('-').map(Number)
  return ['','ינואר','פברואר','מרץ','אפריל','מאי','יוני','יולי','אוגוסט','ספטמבר','אוקטובר','נובמבר','דצמבר'][m] + ' ' + y
}
const currYM = () => {
  const d = new Date()
  return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`
}

const getTenancyStatus = (tn: Tenancy): 'active' | 'future' | 'past' => {
  const today = todayStr()
  if (tn.contractEnd && tn.contractEnd < today) return 'past'
  if (tn.contractStart && tn.contractStart > today) return 'future'
  return 'active'
}

const getMonthsInRange = (start: string, end: string): string[] => {
  if (!start || !end) return []
  const result: string[] = []
  const [sy, sm] = start.slice(0,7).split('-').map(Number)
  const [ey, em] = end.slice(0,7).split('-').map(Number)
  let y = sy, m = sm
  while (y < ey || (y === ey && m <= em)) {
    result.push(`${y}-${String(m).padStart(2,'0')}`)
    m++; if (m > 12) { m = 1; y++ }
    if (result.length > 60) break // safety cap
  }
  return result
}

/* ─── Component ──────────────────────────────────────────────── */
type Props = { uid: string | null; lang?: Lang; onBack: () => void; onLogoClick?: () => void; backHandlerRef?: React.MutableRefObject<(() => boolean) | null> }

export function PropertyManagement({ uid, lang = 'he', onBack, onLogoClick, backHandlerRef }: Props) {
  const t = (key: keyof typeof tt.he): string => (tt[lang] as typeof tt.he)[key] as string
  const lsKey = (k: string) =>
    uid ? `bva_${uid.slice(0,8)}_pm_${k}` : `bva_local_pm_${k}`

  const [properties, setProperties] = useState<Property[]>(
    () => JSON.parse(localStorage.getItem(lsKey('properties')) || '[]'))
  const [tenants, setTenants] = useState<Tenant[]>(
    () => JSON.parse(localStorage.getItem(lsKey('tenants')) || '[]'))
  const [tenancies, setTenancies] = useState<Tenancy[]>(
    () => JSON.parse(localStorage.getItem(lsKey('tenancies')) || '[]'))
  const [tasks, setTasks] = useState<PMTask[]>(
    () => JSON.parse(localStorage.getItem(lsKey('tasks')) || '[]'))
  const [tab, setTab] = useState<Tab>('properties')
  const [toast, setToast] = useState<string | null>(null)

  const [propView, setPropView] = useState<'list'|'detail'|'editProp'|'editTenancy'|'addTenant'|'docs'>('list')
  const [selPropId, setSelPropId] = useState<string | null>(null)
  const [selTenancyId, setSelTenancyId] = useState<string | null>(null)
  const [selViewTenancyId, setSelViewTenancyId] = useState<string | null>(null)
  const [financialEditId, setFinancialEditId] = useState<string | null>(null)
  const [financialEditForm, setFinancialEditForm] = useState({ monthlyRent:0, deposit:0, renewalRent:0, hasOption:false })
  const [propForm, setPropForm] = useState<Omit<Property,'id'>>({
    name:'', address:'', monthlyRent:0, deposit:0, notes:''
  })
  const [propFormId, setPropFormId] = useState<string | null>(null)
  const [tenancyForm, setTenancyForm] = useState<Omit<Tenancy,'id'|'payments'>>({
    propertyId:'', tenantId:'', contractStart:'', contractEnd:'', monthlyRent:0, deposit:0, renewalRent:0,
    depositPaid:false, paymentMethod:'', checksDelivered:false, contractSigned:false, isCurrent:true, hasOption:false
  })
  const [docs, setDocs] = useState<TenancyDoc[]>(
    () => JSON.parse(localStorage.getItem(lsKey('docs')) || '[]'))
  const [pendingDocFile, setPendingDocFile] = useState<{file:File; tenancyId:string; propertyId:string} | null>(null)
  const [pendingDocType, setPendingDocType] = useState<TenancyDoc['type']>('contract')
  const [docSearchQuery, setDocSearchQuery] = useState('')
  const docInputRef = useRef<HTMLInputElement>(null)
  const renewalLeadDays = 90

  const goToPmMain = () => { setTab('properties'); setPropView('list'); setSelPropId(null) }

  // Register Android back handler
  useEffect(() => {
    if (!backHandlerRef) return
    backHandlerRef.current = () => {
      if (propView === 'addTenant')   { setPropView('editTenancy'); return true }
      if (propView === 'editTenancy') { setPropView('detail');      return true }
      if (propView === 'editProp')    { setPropView('list');         return true }
      if (propView === 'docs')        { setPropView('list');         return true }
      if (propView === 'detail')      { setSelPropId(null); setPropView('list'); return true }
      return false
    }
  }, [propView, backHandlerRef])

  const [tenantView, setTenantView] = useState<'list'|'edit'>('list')
  const [tenantForm, setTenantForm] = useState<Omit<Tenant,'id'>>({
    name:'', phone:'', email:'', extraPhones:[], notes:'', status:'lead', interestedPropertyId:null
  })
  const [tenantFormId, setTenantFormId] = useState<string | null>(null)

  useFirebaseSync(uid, 'pm_properties', properties, v => setProperties(v as Property[]))
  useFirebaseSync(uid, 'pm_tenants',    tenants,    v => setTenants(v as Tenant[]))
  useFirebaseSync(uid, 'pm_tenancies',  tenancies,  v => setTenancies(v as Tenancy[]))
  useFirebaseSync(uid, 'pm_tasks',      tasks,      v => setTasks(v as PMTask[]))
  useFirebaseSync(uid, 'pm_docs',       docs,       v => setDocs(v as TenancyDoc[]))

  useEffect(() => { localStorage.setItem(lsKey('properties'), JSON.stringify(properties)) }, [properties])
  useEffect(() => { localStorage.setItem(lsKey('tenants'),    JSON.stringify(tenants))    }, [tenants])
  useEffect(() => { localStorage.setItem(lsKey('tenancies'),  JSON.stringify(tenancies))  }, [tenancies])
  useEffect(() => { localStorage.setItem(lsKey('tasks'),      JSON.stringify(tasks))      }, [tasks])
  useEffect(() => { localStorage.setItem(lsKey('docs'),       JSON.stringify(docs))       }, [docs])

  useEffect(() => {
    const generated: PMTask[] = []
    tenancies.forEach(tn => {
      const tnStatus = getTenancyStatus(tn)
      if (tnStatus === 'past') return  // skip past
      const days = tn.contractEnd ? daysLeft(tn.contractEnd) : 999
      if (days <= renewalLeadDays && days >= -30)
        generated.push({ id:`auto_renewal_${tn.id}`, propertyId:tn.propertyId, tenantId:tn.tenantId, tenancyId:tn.id,
          type:'renewal', title:'חידוש חוזה', dueDate:tn.contractEnd, done:false, doneAt:'', autoGenerated:true })
      if (!tn.depositPaid)
        generated.push({ id:`auto_deposit_${tn.id}`, propertyId:tn.propertyId, tenantId:tn.tenantId, tenancyId:tn.id,
          type:'deposit', title:'פיקדון טרם התקבל', dueDate:tn.contractStart||todayStr(), done:false, doneAt:'', autoGenerated:true })
      if (!tn.checksDelivered)
        generated.push({ id:`auto_checks_${tn.id}`, propertyId:tn.propertyId, tenantId:tn.tenantId, tenancyId:tn.id,
          type:'checks', title:"צ'קים / אסמכתה טרם התקבלה", dueDate:tn.contractStart||todayStr(), done:false, doneAt:'', autoGenerated:true })
    })
    setTasks(prev => {
      const manual = prev.filter(t => !t.autoGenerated)
      const merged = generated.map(g => { const ex = prev.find(p => p.id===g.id); return ex ? {...g, done:ex.done, doneAt:ex.doneAt} : g })
      return [...manual, ...merged]
    })
  }, [tenancies])

  const showToast = (msg: string) => { setToast(msg); setTimeout(() => setToast(null), 3000) }

  const DOC_TYPE_LABEL: Record<TenancyDoc['type'],string> = { contract:'חוזה', renewal:'חידוש', receipt:'אסמכתא', other:'אחר' }
  const DOC_TYPE_COLOR: Record<TenancyDoc['type'],string> = { contract:'#6366F1', renewal:'#10B981', receipt:'#F59E0B', other:'#6B7280' }
  const DOC_TYPE_ICON:  Record<TenancyDoc['type'],string> = { contract:'📄', renewal:'🔄', receipt:'🧾', other:'📎' }

  const fmtFileSize = (bytes: number) => bytes < 1024*1024 ? `${(bytes/1024).toFixed(0)}KB` : `${(bytes/1024/1024).toFixed(1)}MB`

  const saveDoc = (file: File, tenancyId: string, propertyId: string, type: TenancyDoc['type']) => {
    const MAX = 8 * 1024 * 1024
    if (file.size > MAX) { alert(`הקובץ גדול מדי (${fmtFileSize(file.size)}). מקסימום 8MB`); return }
    const reader = new FileReader()
    reader.onload = () => {
      const b64 = reader.result as string
      const id = `doc_${Date.now()}`
      try {
        localStorage.setItem(lsKey(`doc_data_${id}`), b64)
      } catch { alert('אין מספיק מקום בזיכרון המכשיר'); return }
      const meta: TenancyDoc = { id, tenancyId, propertyId, name: file.name, type, date: new Date().toISOString().slice(0,10), mimeType: file.type, size: file.size }
      setDocs(prev => [...prev, meta])
      setPendingDocFile(null)
      showToast('✓ מסמך נוסף')
    }
    reader.readAsDataURL(file)
  }

  const deleteDoc = (id: string) => {
    if (!window.confirm('למחוק את המסמך?')) return
    localStorage.removeItem(lsKey(`doc_data_${id}`))
    setDocs(prev => prev.filter(d => d.id !== id))
  }

  const openDoc = (id: string, mimeType: string, name: string) => {
    const b64 = localStorage.getItem(lsKey(`doc_data_${id}`))
    if (!b64) { alert('הקובץ לא נמצא במכשיר זה'); return }
    try {
      const arr = b64.split(',')
      const bstr = atob(arr[1] || arr[0])
      const bytes = new Uint8Array(bstr.length)
      for (let i=0; i<bstr.length; i++) bytes[i] = bstr.charCodeAt(i)
      const blob = new Blob([bytes], { type: mimeType || 'application/octet-stream' })
      const url = URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url; a.target = '_blank'; a.download = name
      a.click()
      setTimeout(() => URL.revokeObjectURL(url), 5000)
    } catch { alert('שגיאה בפתיחת הקובץ') }
  }
  const sendWA = (phone: string, msg: string) => {
    const clean = phone.replace(/\D/g,'').replace(/^0/,'972')
    window.open(`https://wa.me/${clean}?text=${encodeURIComponent(msg)}`, '_blank')
  }

  const shareDocWA = async (phone: string, msg: string, docType: TenancyDoc['type'], tenancyId: string) => {
    const doc = [...docs].filter(d => d.tenancyId===tenancyId && d.type===docType).sort((a,b)=>b.date.localeCompare(a.date))[0]
    if (!doc) { sendWA(phone, msg); return }
    const b64 = localStorage.getItem(lsKey(`doc_data_${doc.id}`))
    if (!b64) { sendWA(phone, msg); return }
    try {
      const base64Data = b64.split(',')[1]
      const bstr = atob(base64Data)
      const bytes = new Uint8Array(bstr.length)
      for (let i=0; i<bstr.length; i++) bytes[i] = bstr.charCodeAt(i)
      const blob = new Blob([bytes], { type: doc.mimeType || 'application/octet-stream' })
      const file = new File([blob], doc.name, { type: doc.mimeType })
      if ((navigator as any).canShare?.({ files:[file] })) {
        await (navigator as any).share({ files:[file], text:msg })
      } else {
        sendWA(phone, msg)
        const url = URL.createObjectURL(blob)
        const a = document.createElement('a'); a.href=url; a.download=doc.name; a.click()
        setTimeout(() => URL.revokeObjectURL(url), 5000)
        showToast('הקובץ הורד — צרף אותו ידנית בוואטסאפ')
      }
    } catch { sendWA(phone, msg) }
  }
  const getPropName   = (id: string) => properties.find(p=>p.id===id)?.name || '—'
  const getTenantName = (id: string) => tenants.find(t=>t.id===id)?.name || '—'
  const updateTenancy = (id: string, patch: Partial<Tenancy>) =>
    setTenancies(prev => prev.map(t => t.id===id ? {...t,...patch} : t))

  const selProp         = properties.find(p => p.id===selPropId) ?? null
  const propTenancies   = tenancies.filter(t => t.propertyId===selPropId).sort((a,b) => b.contractStart.localeCompare(a.contractStart))

  const hasOverlapForProp = (newStart: string, newEnd: string, propId: string, excludeId?: string) =>
    tenancies.some(t => {
      if (t.propertyId !== propId) return false
      if (excludeId && t.id === excludeId) return false
      return newStart <= t.contractEnd && t.contractStart <= newEnd
    })

  const HDR:  React.CSSProperties = { background:'white', borderBottom:'1px solid #E5E7EB', padding:'12px 16px', display:'flex', alignItems:'center', gap:12, position:'sticky', top:0, zIndex:10 }
  const CARD: React.CSSProperties = { background:'white', border:'1px solid #E5E7EB', borderRadius:14, padding:16, marginBottom:12 }
  const INP:  React.CSSProperties = { border:'1.5px solid #E5E7EB', borderRadius:10, padding:'10px 12px', fontSize:15, width:'100%', boxSizing:'border-box' }
  const LBL:  React.CSSProperties = { fontSize:13, color:'#6B7280', fontWeight:600, display:'block', marginBottom:4 }
  const BTN_P: React.CSSProperties = { background:'#6366F1', color:'white', border:'none', borderRadius:10, padding:'8px 16px', fontWeight:700, fontSize:15, cursor:'pointer' }
  const BACK:  React.CSSProperties = { background:'none', border:'none', cursor:'pointer', fontSize:22, color:'#6B7280', padding:'0 4px' }
  const SCROLL: React.CSSProperties = { flex:1, overflowY:'auto', padding:16 }
  /* ════════════════════════════════════════
     TAB 1: Properties — sub-views
  ════════════════════════════════════════ */

  const renderEditProp = () => (
    <div style={{ display:'flex', flexDirection:'column', height:'100dvh', background:'#F9FAFB' }}>
      <div style={HDR}>
        <button style={BACK} onClick={() => setPropView(propFormId ? 'detail' : 'list')}>‹</button>
        <span style={{ fontWeight:700, fontSize:17, flex:1 }}>{propFormId ? 'עריכת נכס' : 'נכס חדש'}</span>
        <button style={BTN_P} onClick={() => {
          if (!propForm.name.trim()) return
          if (propFormId) setProperties(prev => prev.map(p => p.id===propFormId ? {...propForm,id:propFormId} : p))
          else setProperties(prev => [...prev, {...propForm,id:Date.now().toString()}])
          setPropView('list'); showToast('✓ נשמר')
        }}>שמור</button>
      </div>
      <div style={SCROLL}>
        {(['name','address'] as const).map(f => (
          <label key={f} style={{ display:'block', marginBottom:12 }}>
            <span style={LBL}>{f==='name' ? 'שם קצר לנכס' : 'כתובת מלאה'}</span>
            <input style={INP} value={(propForm as any)[f]}
              onChange={e => setPropForm(p=>({...p,[f]:e.target.value}))}
              placeholder={f==='name'?'דירה ת"א':'רחוב הרצל 5'} />
          </label>
        ))}
        <div style={{ display:'grid', gridTemplateColumns:'1fr 1fr', gap:10, marginBottom:12 }}>
          <label>
            <span style={LBL}>שכ"ד חודשי (₪)</span>
            <input style={INP} type="number" value={propForm.monthlyRent||''}
              onChange={e=>setPropForm(p=>({...p,monthlyRent:Number(e.target.value)}))} />
          </label>
          <label>
            <span style={LBL}>פיקדון (₪)</span>
            <input style={INP} type="number" value={propForm.deposit||''}
              onChange={e=>setPropForm(p=>({...p,deposit:Number(e.target.value)}))} />
          </label>
        </div>
        <label style={{ display:'block', marginBottom:12 }}>
          <span style={LBL}>הערות</span>
          <textarea style={{...INP,resize:'none'}} value={propForm.notes}
            onChange={e=>setPropForm(p=>({...p,notes:e.target.value}))} rows={3}/>
        </label>
        {propFormId && (
          <button type="button" onClick={() => {
            setProperties(prev=>prev.filter(p=>p.id!==propFormId))
            setTenancies(prev=>prev.filter(t=>t.propertyId!==propFormId))
            setPropView('list'); showToast('נמחק')
          }} style={{ width:'100%', padding:12, background:'#FEF2F2', border:'1px solid #FECACA', borderRadius:10, color:'#DC2626', fontWeight:600, cursor:'pointer' }}>
            🗑 מחק נכס
          </button>
        )}
      </div>
    </div>
  )

  const renderEditTenancy = () => (
    <div style={{ display:'flex', flexDirection:'column', height:'100dvh', background:'#F9FAFB' }}>
      <div style={HDR}>
        <button style={BACK} onClick={() => setPropView('detail')}>‹</button>
        <span style={{ fontWeight:700, fontSize:17, flex:1 }}>{selTenancyId ? 'עריכת שכירות' : 'קישור שוכר לנכס'}</span>
        <button style={BTN_P} onClick={() => {
          if (!tenancyForm.tenantId || !tenancyForm.contractStart) return
          if (!tenancyForm.contractStart || !tenancyForm.contractEnd) { alert('חסרים תאריכי חוזה'); return }
          if (tenancyForm.contractStart > tenancyForm.contractEnd) { alert('תאריך התחלה חייב להיות לפני תאריך הסיום'); return }
          const overlapExists = hasOverlapForProp(tenancyForm.contractStart, tenancyForm.contractEnd, tenancyForm.propertyId, selTenancyId || undefined)
          if (overlapExists && !window.confirm('⚠️ תקופה זו חופפת לחוזה קיים. האם להמשיך בכל זאת?')) return
          const id = selTenancyId || `ten_${Date.now()}`
          const existing = selTenancyId ? tenancies.find(t=>t.id===selTenancyId) : null
          const rec: Tenancy = { ...tenancyForm, id, payments: existing?.payments || {} }
          if (selTenancyId) setTenancies(prev => prev.map(t => t.id===selTenancyId ? rec : t))
          else setTenancies(prev => [...prev, rec])
          setSelViewTenancyId(id)
          setPropView('detail'); showToast('✓ שכירות נשמרה')
        }}>שמור</button>
      </div>
      <div style={SCROLL}>
        <label style={{ display:'block', marginBottom:12 }}>
          <span style={LBL}>שוכר</span>
          <select style={INP} value={tenancyForm.tenantId}
            onChange={e=>setTenancyForm(f=>({...f,tenantId:e.target.value}))}>
            <option value="">בחר שוכר...</option>
            {tenants.map(t=><option key={t.id} value={t.id}>{t.name}{t.phone ? ` — ${t.phone}` : ''}</option>)}
          </select>
        </label>
        <div style={{ textAlign:'center', marginBottom:14 }}>
          <button type="button" onClick={() => {
            setTenantForm({name:'',phone:'',email:'',extraPhones:[],notes:'',status:'active',interestedPropertyId:selPropId})
            setTenantFormId(null); setPropView('addTenant')
          }} style={{ background:'#EFF6FF', border:'1px solid #BFDBFE', borderRadius:10, padding:'8px 16px', color:'#1D4ED8', fontWeight:600, cursor:'pointer', fontSize:13 }}>
            + הוסף שוכר חדש
          </button>
        </div>
        <div style={{ display:'grid', gridTemplateColumns:'1fr 1fr', gap:10, marginBottom:12 }}>
          <label>
            <span style={LBL}>תחילת חוזה</span>
            <input style={INP} type="date" value={tenancyForm.contractStart}
              onChange={e=>setTenancyForm(f=>({...f,contractStart:e.target.value}))} />
          </label>
          <label>
            <span style={LBL}>סוף חוזה</span>
            <input style={INP} type="date" value={tenancyForm.contractEnd}
              onChange={e=>setTenancyForm(f=>({...f,contractEnd:e.target.value}))} />
          </label>
        </div>
        <div style={{ display:'grid', gridTemplateColumns:'1fr 1fr 1fr', gap:10, marginBottom:12 }}>
          <label>
            <span style={LBL}>שכ"ד חודשי (₪)</span>
            <input style={INP} type="number" value={tenancyForm.monthlyRent||''}
              onChange={e=>setTenancyForm(f=>({...f,monthlyRent:Number(e.target.value)}))} />
          </label>
          <label>
            <span style={LBL}>פיקדון (₪)</span>
            <input style={INP} type="number" value={(tenancyForm as any).deposit||''}
              onChange={e=>setTenancyForm(f=>({...f,deposit:Number(e.target.value)}))} />
          </label>
          <label>
            <span style={LBL}>שכ"ד חידוש (₪)</span>
            <input style={INP} type="number" value={tenancyForm.renewalRent||''}
              onChange={e=>setTenancyForm(f=>({...f,renewalRent:Number(e.target.value)||undefined}))} />
          </label>
        </div>
        <label style={{ display:'block', marginBottom:12 }}>
          <span style={LBL}>אמצעי תשלום</span>
          <select style={INP} value={tenancyForm.paymentMethod}
            onChange={e=>setTenancyForm(f=>({...f,paymentMethod:e.target.value as any}))}>
            <option value="">בחר...</option>
            <option value="checks">המחאות</option>
            <option value="bank">העברה בנקאית</option>
            <option value="cash">מזומן</option>
          </select>
        </label>
        <div style={{ background:'white', borderRadius:12, padding:14, border:'1px solid #E5E7EB', display:'flex', flexDirection:'column', gap:10 }}>
          <div style={{ fontWeight:700, fontSize:13, color:'#374151', marginBottom:4 }}>✅ סטטוס</div>
          {([
            {k:'depositPaid',l:'פיקדון התקבל'},
            {k:'checksDelivered',l:"צ'קים / אסמכתה התקבלה"},
            {k:'contractSigned',l:'חוזה חתום'},
            {k:'isCurrent',l:'שכירות פעילה'},
            {k:'hasOption',l:'יש אופציה (אופשיית חידוש לשוכר)'},
          ] as const).map(({k,l}) => (
            <label key={k} style={{ display:'flex', alignItems:'center', gap:10, cursor:'pointer' }}>
              <input type="checkbox" checked={(tenancyForm as any)[k]}
                onChange={e=>setTenancyForm(f=>({...f,[k]:e.target.checked}))}
                style={{width:18,height:18}} />
              <span style={{ fontSize:14, fontWeight:500 }}>{l}</span>
            </label>
          ))}
        </div>
      </div>
    </div>
  )
  const renderAddTenantInline = () => (
    <div style={{ display:'flex', flexDirection:'column', height:'100dvh', background:'#F9FAFB' }}>
      <div style={HDR}>
        <button style={BACK} onClick={() => setPropView('editTenancy')}>‹</button>
        <span style={{ fontWeight:700, fontSize:17, flex:1 }}>שוכר חדש</span>
        <button style={BTN_P} onClick={() => {
          if (!tenantForm.name.trim()) return
          const id = Date.now().toString()
          setTenants(prev => [...prev, {...tenantForm, id}])
          setTenancyForm(f => ({...f, tenantId:id}))
          setPropView('editTenancy'); showToast('✓ שוכר נוצר')
        }}>שמור</button>
      </div>
      <div style={SCROLL}>
        {([{f:'name',l:'שם מלא',t:'text'},{f:'phone',l:'טלפון',t:'tel'},{f:'email',l:'דוא"ל',t:'email'}] as const).map(({f,l,t}) => (
          <label key={f} style={{ display:'block', marginBottom:12 }}>
            <span style={LBL}>{l}</span>
            <input style={INP} type={t} value={(tenantForm as any)[f]}
              onChange={e=>setTenantForm(p=>({...p,[f]:e.target.value}))} />
          </label>
        ))}
      </div>
    </div>
  )

  const renderPropDetail = () => {
    if (!selProp) return null
    const p = selProp
    const ym = currYM()
    const STATUS_COLOR: Record<string,string> = { active:'#22C55E', future:'#6366F1', past:'#9CA3AF' }
    const STATUS_LABEL: Record<string,string>  = { active:'פעיל', future:'עתידי', past:'עבר' }
    const PMT_COLOR = (s?: string) => s==='paid'?'#22C55E':s==='late'?'#EF4444':'#F59E0B'
    const handleBack = () => {
      if (selViewTenancyId) setSelViewTenancyId(null)
      else { setPropView('list') }
    }
    return (
      <div style={{ display:'flex', flexDirection:'column', height:'100dvh', background:'#F9FAFB' }}>
        <div style={HDR}>
          <button style={{ background:'none', border:'none', cursor:'pointer', padding:'0 4px', display:'flex', alignItems:'center', height:32 }} onClick={handleBack}>
            <img src="/Trn color.png" alt="חזור" style={{ height:22 }} />
          </button>
          <span style={{ fontWeight:700, fontSize:17, flex:1 }}>{p.name || p.address}</span>
          <button type="button" onClick={() => {
            setPropFormId(p.id)
            setPropForm({name:p.name,address:p.address,monthlyRent:p.monthlyRent,deposit:p.deposit,notes:p.notes})
            setPropView('editProp')
          }} style={{ background:'#F3F4F6', border:'none', borderRadius:8, padding:'6px 12px', fontWeight:600, cursor:'pointer', color:'#374151', fontSize:13 }}>ערוך</button>
        </div>
        <div style={SCROLL}>

          {/* ── Property info bar ── */}
          <div style={{ background:'white', borderRadius:14, padding:'12px 16px', marginBottom:12, border:'1px solid #E5E7EB', display:'flex', justifyContent:'space-between', alignItems:'center' }}>
            <div>
              <div style={{ fontSize:12, color:'#6B7280' }}>📍 {p.address}</div>
              {p.notes && <div style={{ marginTop:4, fontSize:12, color:'#92400E' }}>📝 {p.notes}</div>}
            </div>
            <div style={{ textAlign:'left' }}>
              <div style={{ fontWeight:700, fontSize:16, color:'#111827' }}>{fmtMoney(p.monthlyRent)}</div>
              {p.deposit>0 && <div style={{ fontSize:11, color:'#6B7280' }}>פיקדון {fmtMoney(p.deposit)}</div>}
            </div>
          </div>

          {/* ── Tenancy accordion ── */}
          <div style={CARD}>
            <div style={{ display:'flex', justifyContent:'space-between', alignItems:'center', marginBottom:12 }}>
              <div style={{ fontWeight:700, fontSize:14 }}>📅 תקופות שכירות</div>
              <button type="button" onClick={() => {
                setSelTenancyId(null)
                setTenancyForm({propertyId:p.id,tenantId:'',contractStart:'',contractEnd:'',monthlyRent:p.monthlyRent,deposit:p.deposit||0,renewalRent:0,depositPaid:false,paymentMethod:'',checksDelivered:false,contractSigned:false,isCurrent:true,hasOption:false})
                setPropView('editTenancy')
              }} style={{ background:'#6366F1', color:'white', border:'none', borderRadius:8, padding:'5px 12px', fontWeight:700, cursor:'pointer', fontSize:12 }}>+ הוסף תקופה</button>
            </div>

            {propTenancies.length === 0 ? (
              <div style={{ textAlign:'center', padding:'16px', color:'#9CA3AF', fontSize:13 }}>אין תקופות שכירות — לחץ "הוסף תקופה"</div>
            ) : (
              <div style={{ display:'flex', flexDirection:'column', gap:10 }}>
                {propTenancies.map(t => {
                  const st    = getTenancyStatus(t)
                  const sc    = STATUS_COLOR[st]
                  const t_tnt = tenants.find(x => x.id===t.tenantId)
                  const days2 = t.contractEnd ? daysLeft(t.contractEnd) : null
                  const isOpen = selViewTenancyId === t.id
                  return (
                    <div key={t.id} style={{ borderRadius:14, overflow:'hidden', border:`2px solid ${isOpen ? sc : '#E5E7EB'}`, background:'white' }}>

                      {/* ── Card header (contract title row) ── */}
                      <div style={{ display:'flex', alignItems:'stretch', background:isOpen ? sc+'14' : 'white' }}>
                        <button type="button" onClick={() => setSelViewTenancyId(isOpen ? null : t.id)}
                          style={{ flex:1, background:'none', border:'none', padding:'12px 14px', cursor:'pointer', textAlign:'right', display:'flex', alignItems:'center', gap:10 }}>
                          <div style={{ flex:1, minWidth:0 }}>
                            <div style={{ fontWeight:800, fontSize:15, color:'#111827', marginBottom:3 }}>{t_tnt?.name || '—'}</div>
                            <div style={{ display:'flex', alignItems:'center', gap:5, flexWrap:'wrap' }}>
                              <span style={{ fontWeight:700, fontSize:13, color:sc, direction:'ltr' }}>{t.contractStart.split('-').reverse().map((x,i)=>i===2?x.slice(2):x).join('/')}</span>
                              <span style={{ color:'#9CA3AF', fontSize:12 }}>→</span>
                              <span style={{ fontWeight:700, fontSize:13, color:sc, direction:'ltr' }}>{t.contractEnd.split('-').reverse().map((x,i)=>i===2?x.slice(2):x).join('/')}</span>
                              {days2!==null && st!=='past' && <span style={{ fontSize:11, color:'#9CA3AF' }}>· {days2<0?t('expired'):st==='future'?`בעוד ${Math.abs(daysLeft(t.contractStart))}י'`:(tt[lang].daysToEnd as (n:number)=>string)(days2)}</span>}
                            </div>
                          </div>
                          <div style={{ display:'flex', alignItems:'center', gap:6, flexShrink:0 }}>
                            <span style={{ fontSize:11, background:sc+'20', color:sc, borderRadius:20, padding:'2px 8px', fontWeight:700 }}>{STATUS_LABEL[st]}</span>
                            <span style={{ fontSize:14, color:sc }}>{isOpen ? '▲' : '▼'}</span>
                          </div>
                        </button>
                        {/* Edit + Delete in header */}
                        <div style={{ display:'flex', alignItems:'center', gap:2, padding:'0 8px', borderRight:`1px solid ${sc}30` }}>
                          <button type="button" title="ערוך הסכם" onClick={() => {
                            setSelTenancyId(t.id)
                            setTenancyForm({propertyId:t.propertyId,tenantId:t.tenantId,contractStart:t.contractStart,contractEnd:t.contractEnd,monthlyRent:t.monthlyRent,deposit:t.deposit||0,renewalRent:t.renewalRent||0,depositPaid:t.depositPaid,paymentMethod:t.paymentMethod,checksDelivered:t.checksDelivered,contractSigned:t.contractSigned,isCurrent:t.isCurrent,hasOption:t.hasOption||false})
                            setPropView('editTenancy')
                          }} style={{ background:'none', border:'none', borderRadius:8, padding:'6px 8px', cursor:'pointer', fontSize:18, lineHeight:1 }}>✏️</button>
                          <button type="button" title="מחק הסכם" onClick={() => {
                            if (!window.confirm(`למחוק את ההסכם עם ${t_tnt?.name||'השוכר'}? פעולה זו אינה הפיכה.`)) return
                            setTenancies(prev => prev.filter(x => x.id !== t.id))
                            setSelViewTenancyId(null)
                          }} style={{ background:'none', border:'none', borderRadius:8, padding:'6px 8px', cursor:'pointer', fontSize:18, lineHeight:1 }}>🗑️</button>
                        </div>
                      </div>

                      {/* ── Accordion body ── */}
                      {isOpen && (
                        <div style={{ borderTop:`2px solid ${sc}30`, padding:'14px' }}>
                          {!t_tnt ? (
                            <div style={{ textAlign:'center', color:'#9CA3AF', fontSize:13, padding:'10px 0' }}>שוכר לא נמצא — ערוך את התקופה</div>
                          ) : (
                            <>
                              {/* Financial summary strip */}
                              <div style={{ display:'flex', gap:6, marginBottom:10, flexWrap:'wrap', alignItems:'center' }}>
                                <span style={{ fontSize:12, background:'#ECFDF5', color:'#059669', borderRadius:8, padding:'4px 10px', fontWeight:600 }}>💳 {fmtMoney(t.monthlyRent||p.monthlyRent)}/חודש</span>
                                {t.deposit ? <span style={{ fontSize:12, background:'#EFF6FF', color:'#1D4ED8', borderRadius:8, padding:'4px 10px', fontWeight:600 }}>💰 פיקדון: {fmtMoney(t.deposit)}</span> : <span style={{ fontSize:12, background:'#F3F4F6', color:'#9CA3AF', borderRadius:8, padding:'4px 10px' }}>💰 פיקדון: לא הוגדר</span>}
                                {t.renewalRent ? <span style={{ fontSize:12, background:'#FAF5FF', color:'#5B21B6', borderRadius:8, padding:'4px 10px', fontWeight:600 }}>🔄 חידוש: {fmtMoney(t.renewalRent)}</span> : <span style={{ fontSize:12, background:'#F3F4F6', color:'#9CA3AF', borderRadius:8, padding:'4px 10px' }}>🔄 חידוש: לא הוגדר</span>}
                                {t.hasOption && <span style={{ fontSize:11, background:'#FEF3C7', color:'#92400E', borderRadius:8, padding:'3px 8px', fontWeight:700 }}>⭐ אופציה</span>}
                              </div>
                              {/* Contact info */}
                              {(t_tnt.phone || t_tnt.email) && (
                                <div style={{ fontSize:12, color:'#6B7280', marginBottom:10 }}>
                                  {t_tnt.phone && <span style={{ marginLeft:12 }}>📞 {t_tnt.phone}</span>}
                                  {t_tnt.email && <span>✉ {t_tnt.email}</span>}
                                </div>
                              )}
                              {/* Checklist + inline WA */}
                              <div style={{ display:'flex', flexDirection:'column', gap:8, marginBottom:14 }}>
                                {([
                                  {k:'depositPaid' as const, l:'פיקדון התקבל', waIcon:'💰', waBg:'#EFF6FF', waBc:'#BFDBFE', waC:'#1D4ED8', waMsg:`שלום ${t_tnt.name}, תזכורת להעברת פיקדון (${fmtMoney(t.deposit ?? p.deposit)}) עבור ${p.name}. תודה 🙏`},
                                  {k:'checksDelivered' as const, l:"צ'קים / אסמכתא", waIcon:'📑', waBg:'#FFF7ED', waBc:'#FED7AA', waC:'#C2410C', waMsg:`שלום ${t_tnt.name}, תזכורת לשלוח צ'קים / אסמכתה עבור ${p.name}. תודה 🙏`},
                                  {k:'contractSigned' as const, l:'חוזה חתום', waIcon:'✍️', waBg:'#F0FDF4', waBc:'#BBF7D0', waC:'#15803D', waMsg:`שלום ${t_tnt.name}, אנא חתום על חוזה השכירות עבור ${p.name} ושלח חזרה. תודה 🙏`},
                                ]).map(({k,l,waIcon,waBg,waBc,waC,waMsg}) => {
                                  const val = t[k]
                                  return (
                                    <div key={k} style={{ display:'flex', alignItems:'center', gap:8 }}>
                                      <button type="button" onClick={() => updateTenancy(t.id,{[k]:!val} as any)}
                                        style={{ flex:1, display:'flex', alignItems:'center', gap:10, background:val?'#F0FDF4':'white', border:val?'1px solid #BBF7D0':'1px solid #E5E7EB', borderRadius:8, padding:'8px 12px', cursor:'pointer', textAlign:'right' }}>
                                        <span style={{ fontSize:18, color:val?'#16A34A':'#9CA3AF' }}>{val?'✅':'☐'}</span>
                                        <span style={{ fontSize:13, fontWeight:600, color:val?'#15803D':'#374151' }}>{l}</span>
                                      </button>
                                      <button type="button" onClick={() => t_tnt.phone ? (k==='contractSigned' ? shareDocWA(t_tnt.phone, waMsg, 'contract', t.id) : sendWA(t_tnt.phone, waMsg)) : alert('אין טלפון רשום')}
                                        style={{ background:waBg, border:`1px solid ${waBc}`, color:waC, borderRadius:8, padding:'8px 12px', fontWeight:700, cursor:'pointer', fontSize:16, flexShrink:0 }}>{waIcon}</button>
                                      {k==='contractSigned' && (
                                        <button type="button" title="צרף חוזה" onClick={() => {
                                          if (!docInputRef.current) return
                                          docInputRef.current.setAttribute('data-tid', t.id)
                                          docInputRef.current.setAttribute('data-pid', t.propertyId)
                                          setPendingDocType('contract')
                                          docInputRef.current.click()
                                        }} style={{ background:'#F5F3FF', border:'1px solid #DDD6FE', color:'#7C3AED', borderRadius:8, padding:'8px 10px', fontWeight:700, cursor:'pointer', fontSize:15, flexShrink:0 }}>📎</button>
                                      )}
                                    </div>
                                  )
                                })}
                                {/* חידוש חוזה — indicator row + WA */}
                                {(() => {
                                  const hasRenewal = tasks.some(tk => tk.tenancyId===t.id && tk.type==='renewal' && !tk.done)
                                  return (
                                    <div style={{ display:'flex', alignItems:'center', gap:8 }}>
                                      <div style={{ flex:1, display:'flex', alignItems:'center', gap:8, background:hasRenewal?'#FAF5FF':'white', border:`1px solid ${hasRenewal?'#DDD6FE':'#E5E7EB'}`, borderRadius:8, padding:'8px 10px' }}>
                                        <span style={{ fontSize:18, flexShrink:0 }}>{hasRenewal?'🔄':'○'}</span>
                                        <span style={{ fontSize:13, fontWeight:600, color:hasRenewal?'#5B21B6':'#374151', flexShrink:0 }}>חידוש חוזה</span>
                                        {hasRenewal && <span style={{ fontSize:10, background:'#7C3AED20', color:'#7C3AED', borderRadius:10, padding:'1px 5px', fontWeight:700, flexShrink:0 }}>משימה פתוחה</span>}
                                      </div>
                                      <button type="button" onClick={() => t_tnt.phone ? shareDocWA(t_tnt.phone, `שלום ${t_tnt.name}, תזכורת לחידוש חוזה השכירות עבור ${p.name}. החוזה מסתיים ב-${t.contractEnd}. האם ברצונך לחדש? 🙏`, 'renewal', t.id) : alert('אין טלפון רשום')}
                                        style={{ background:'#F5F3FF', border:'1px solid #DDD6FE', color:'#7C3AED', borderRadius:8, padding:'8px 12px', fontWeight:700, cursor:'pointer', fontSize:16, flexShrink:0 }}>🔄</button>
                                      <button type="button" title="צרף חידוש" onClick={() => {
                                        if (!docInputRef.current) return
                                        docInputRef.current.setAttribute('data-tid', t.id)
                                        docInputRef.current.setAttribute('data-pid', t.propertyId)
                                        setPendingDocType('renewal')
                                        docInputRef.current.click()
                                      }} style={{ background:'#F0FDF4', border:'1px solid #BBF7D0', color:'#15803D', borderRadius:8, padding:'8px 10px', fontWeight:700, cursor:'pointer', fontSize:15, flexShrink:0 }}>📎</button>
                                    </div>
                                  )
                                })()}
                              </div>

                              {/* Documents */}
                              {renderDocSection(t)}

                              {/* Payment tracker */}
                              <div style={{ borderTop:'1px solid #F3F4F6', paddingTop:12, marginBottom:14 }}>
                                <div style={{ fontWeight:700, fontSize:13, marginBottom:10, color:'#374151' }}>💳 מעקב תשלומים</div>
                                <div style={{ display:'flex', flexDirection:'column', gap:6 }}>
                                  {getMonthsInRange(t.contractStart, t.contractEnd).map(m => {
                                    const status = t.payments?.[m]
                                    const isCurr = m === ym
                                    const isFuture = m > ym
                                    return (
                                      <div key={m} style={{ display:'flex', alignItems:'center', gap:8, padding:'8px 10px', borderRadius:10, background:isCurr?'#EFF6FF':'#F9FAFB', border:isCurr?'1.5px solid #BFDBFE':'1px solid #F3F4F6' }}>
                                        <div style={{ flex:1 }}>
                                          <span style={{ fontWeight:isCurr?800:600, fontSize:13, color:isCurr?'#1D4ED8':'#374151' }}>{monthLabel(m)}</span>
                                          {isCurr && <span style={{ fontSize:10, color:'#6366F1', marginRight:6, background:'#EEF2FF', borderRadius:10, padding:'1px 6px' }}>נוכחי</span>}
                                        </div>
                                        {isCurr && (
                                          <button type="button" onClick={() => t_tnt.phone ? sendWA(t_tnt.phone, `שלום ${t_tnt.name}, תזכורת לתשלום שכ"ד חודש ${monthLabel(m)} עבור ${p.name}: ${fmtMoney(t.monthlyRent||p.monthlyRent)}. תודה 🙏`) : alert('אין טלפון רשום')}
                                            style={{ background:'#F5F3FF', border:'1px solid #DDD6FE', color:'#7C3AED', borderRadius:7, padding:'5px 8px', fontWeight:700, cursor:'pointer', fontSize:14, flexShrink:0 }}>💬</button>
                                        )}
                                        <div style={{ display:'flex', gap:4 }}>
                                          {(['paid','pending','late'] as const).map(s => (
                                            <button key={s} type="button"
                                              onClick={() => updateTenancy(t.id, {payments:{...t.payments,[m]:s}})}
                                              style={{ padding:'5px 8px', borderRadius:7, border:'none', cursor:'pointer', fontSize:11, fontWeight:700,
                                                background:status===s?(s==='paid'?'#22C55E':s==='late'?'#EF4444':'#F59E0B'):(isFuture?'#F3F4F6':'#E5E7EB'),
                                                color:status===s?'white':(isFuture?'#D1D5DB':'#6B7280') }}>
                                              {s==='paid'?'✓':s==='late'?'⚠':'⏳'}
                                            </button>
                                          ))}
                                          {status && <span style={{ fontSize:11, color:PMT_COLOR(status), fontWeight:700, padding:'4px 0', minWidth:32, textAlign:'center' }}>
                                            {status==='paid'?'שולם':status==='late'?'מאחר':'ממתין'}
                                          </span>}
                                        </div>
                                      </div>
                                    )
                                  })}
                                </div>
                              </div>
                            </>
                          )}
                        </div>
                      )}
                    </div>
                  )
                })}
              </div>
            )}
          </div>

          {/* Hidden file input */}
          <input ref={docInputRef} type="file" accept="image/*,application/pdf,.doc,.docx,.xls,.xlsx" style={{ display:'none' }}
            onChange={e => {
              const file = e.target.files?.[0]
              if (!file) return
              const tid = docInputRef.current?.getAttribute('data-tid') || ''
              const pid = docInputRef.current?.getAttribute('data-pid') || ''
              setPendingDocFile({ file, tenancyId: tid, propertyId: pid })
              setPendingDocType('contract')
              e.target.value = ''
            }} />
        </div>
      </div>
    )
  }
  const renderPropList = () => (
    <>
      <div style={HDR}>
        <button style={{ background:'none', border:'none', cursor:'pointer', padding:'0 4px', display:'flex', alignItems:'center', height:32 }} onClick={onLogoClick ?? onBack}>
          <img src="/Trn color.png" alt="חזור" style={{ height:22 }} />
        </button>
        <span style={{ fontWeight:700, fontSize:17, flex:1 }}>🏠 {t('tabProperties')}</span>
        <button type="button" onClick={() => { setDocSearchQuery(''); setPropView('docs') }}
          style={{ background:'#F5F3FF', border:'none', borderRadius:8, padding:'6px 10px', color:'#7C3AED', fontWeight:700, cursor:'pointer', fontSize:12, marginLeft:6 }}>
          📄 {docs.length > 0 ? docs.length : ''}
        </button>
        <button style={BTN_P} onClick={() => {
          setPropFormId(null); setPropForm({name:'',address:'',monthlyRent:0,deposit:0,notes:''}); setPropView('editProp')
        }}>+ נכס</button>
      </div>
      <div style={SCROLL}>
        {properties.length===0 ? (
          <div style={{ textAlign:'center', padding:'60px 20px', color:'#9CA3AF' }}>
            <div style={{ fontSize:48, marginBottom:12 }}>🏠</div>
            <div style={{ fontWeight:700, fontSize:16, color:'#374151', marginBottom:6 }}>{t('noPropertiesYet')}</div>
            <div style={{ fontSize:14 }}>{t('clickToAddProperty')}</div>
          </div>
        ) : properties.map(p => {
          const allPropTn = tenancies.filter(t=>t.propertyId===p.id)
          const ct = allPropTn.find(t=>getTenancyStatus(t)==='active') ?? allPropTn.find(t=>getTenancyStatus(t)==='future') ?? null
          const ctn = ct ? tenants.find(t=>t.id===ct.tenantId) : null
          const ctStatus = ct ? getTenancyStatus(ct) : null
          const days = ct?.contractEnd ? daysLeft(ct.contractEnd) : null
          const urg = days===null ? '#9CA3AF' : days<0 ? '#EF4444' : days<=60 ? '#F59E0B' : '#22C55E'
          return (
            <button key={p.id} type="button" onClick={() => { setSelPropId(p.id); setPropView('detail') }}
              style={{ ...CARD, width:'100%', textAlign:'right', cursor:'pointer', display:'flex', flexDirection:'column', gap:8 }}>
              <div style={{ display:'flex', justifyContent:'space-between', alignItems:'flex-start' }}>
                <div style={{ flex:1 }}>
                  <div style={{ fontWeight:700, fontSize:16, color:'#111827' }}>{p.name || p.address}</div>
                  <div style={{ fontSize:12, color:'#6B7280' }}>{p.address}</div>
                </div>
                {days!==null && (
                  <span style={{ fontSize:11, background:urg+'20', color:urg, borderRadius:20, padding:'2px 8px', fontWeight:700, marginRight:8, whiteSpace:'nowrap' }}>
                    {days<0 ? t('expired') : `${days}י'`}
                  </span>
                )}
              </div>
              <div style={{ display:'flex', justifyContent:'space-between', alignItems:'center' }}>
                <span style={{ fontWeight:700, fontSize:15, color:'#111827' }}>{fmtMoney(p.monthlyRent)}/חודש</span>
                <span style={{ fontSize:13, color:ctn?'#374151':'#9CA3AF' }}>{ctn ? `${ctn.name}${ctStatus==='future'?` (${t('legendFuture')})`:''}` : t('vacant')}</span>
              </div>
            </button>
          )
        })}
      </div>
      {properties.length>0 && (
        <div style={{ background:'white', borderTop:'1px solid #E5E7EB', padding:'12px 20px', display:'flex', justifyContent:'space-around', flexShrink:0 }}>
          <div style={{ textAlign:'center' }}><div style={{ fontSize:18, fontWeight:700 }}>{properties.length}</div><div style={{ fontSize:11, color:'#6B7280' }}>{t('propertiesCount')}</div></div>
          <div style={{ textAlign:'center' }}><div style={{ fontSize:18, fontWeight:700, color:'#22C55E' }}>{fmtMoney(properties.reduce((s,p)=>s+p.monthlyRent,0))}</div><div style={{ fontSize:11, color:'#6B7280' }}>{t('monthlyRentKpi')}</div></div>
          <div style={{ textAlign:'center' }}><div style={{ fontSize:18, fontWeight:700, color:'#6366F1' }}>{properties.filter(p=>tenancies.some(tn=>tn.propertyId===p.id&&getTenancyStatus(tn)==='active')).length}</div><div style={{ fontSize:11, color:'#6B7280' }}>{t('rentedCount')}</div></div>
        </div>
      )}
    </>
  )

  /* ── Per-tenancy document attachment section ── */
  const renderDocSection = (tn: Tenancy) => {
    const tnDocs = docs.filter(d => d.tenancyId === tn.id)
    const isPending = pendingDocFile?.tenancyId === tn.id
    return (
      <div style={{ borderTop:'1px solid #F3F4F6', paddingTop:14, marginTop:4 }}>
        <div style={{ display:'flex', justifyContent:'space-between', alignItems:'center', marginBottom:10 }}>
          <div style={{ fontWeight:700, fontSize:13, color:'#374151' }}>📎 מסמכים {tnDocs.length > 0 && <span style={{ fontSize:11, background:'#EEF2FF', color:'#6366F1', borderRadius:10, padding:'1px 7px', fontWeight:700 }}>{tnDocs.length}</span>}</div>
          <button type="button" onClick={() => {
            setPendingDocFile(null)
            setPendingDocType('contract')
            docInputRef.current?.click()
            // store context for when file is selected
            docInputRef.current?.setAttribute('data-tid', tn.id)
            docInputRef.current?.setAttribute('data-pid', tn.propertyId)
          }} style={{ background:'#6366F1', color:'white', border:'none', borderRadius:8, padding:'5px 12px', fontWeight:700, cursor:'pointer', fontSize:12 }}>
            + הוסף מסמך
          </button>
        </div>

        {/* Pending file — type picker */}
        {isPending && pendingDocFile && (
          <div style={{ background:'#EEF2FF', borderRadius:12, padding:'12px 14px', marginBottom:12, border:'1.5px solid #A5B4FC' }}>
            <div style={{ fontSize:12, fontWeight:700, color:'#4338CA', marginBottom:8 }}>📂 {pendingDocFile.file.name} ({fmtFileSize(pendingDocFile.file.size)})</div>
            <div style={{ fontSize:12, color:'#374151', marginBottom:8, fontWeight:600 }}>סוג מסמך:</div>
            <select value={pendingDocType} onChange={e => setPendingDocType(e.target.value as TenancyDoc['type'])}
              style={{ width:'100%', padding:'8px 10px', borderRadius:8, border:'1.5px solid #A5B4FC', fontSize:13, fontWeight:600, marginBottom:10, background:'white', color:'#374151', cursor:'pointer' }}>
              {(['contract','renewal','receipt','other'] as TenancyDoc['type'][]).map(tp => (
                <option key={tp} value={tp}>{DOC_TYPE_ICON[tp]} {DOC_TYPE_LABEL[tp]}</option>
              ))}
            </select>
            <div style={{ display:'flex', gap:8 }}>
              <button type="button" onClick={() => saveDoc(pendingDocFile.file, pendingDocFile.tenancyId, pendingDocFile.propertyId, pendingDocType)}
                style={{ flex:1, background:'#6366F1', color:'white', border:'none', borderRadius:8, padding:'8px', fontWeight:700, cursor:'pointer', fontSize:13 }}>שמור</button>
              <button type="button" onClick={() => setPendingDocFile(null)}
                style={{ background:'#F3F4F6', border:'none', borderRadius:8, padding:'8px 14px', color:'#6B7280', fontWeight:600, cursor:'pointer', fontSize:13 }}>{t('cancel')}</button>
            </div>
          </div>
        )}

        {/* Doc list */}
        {tnDocs.length === 0 && !isPending ? (
          <div style={{ fontSize:12, color:'#9CA3AF', textAlign:'center', padding:'10px 0' }}>אין מסמכים מצורפים</div>
        ) : (
          <div style={{ display:'flex', flexDirection:'column', gap:8 }}>
            {tnDocs.map(d => {
              const hasData = !!localStorage.getItem(lsKey(`doc_data_${d.id}`))
              return (
                <div key={d.id} style={{ display:'flex', alignItems:'center', gap:10, background:'#F9FAFB', borderRadius:10, padding:'10px 12px', border:'1px solid #E5E7EB' }}>
                  <span style={{ fontSize:20, flexShrink:0 }}>{DOC_TYPE_ICON[d.type]}</span>
                  <div style={{ flex:1, minWidth:0 }}>
                    <div style={{ fontWeight:600, fontSize:13, color:'#111827', whiteSpace:'nowrap', overflow:'hidden', textOverflow:'ellipsis' }}>{d.name}</div>
                    <div style={{ display:'flex', gap:6, alignItems:'center', marginTop:2 }}>
                      <span style={{ fontSize:10, background:DOC_TYPE_COLOR[d.type]+'20', color:DOC_TYPE_COLOR[d.type], borderRadius:10, padding:'1px 7px', fontWeight:700 }}>{DOC_TYPE_LABEL[d.type]}</span>
                      <span style={{ fontSize:10, color:'#9CA3AF' }}>{d.date} · {fmtFileSize(d.size)}</span>
                      {!hasData && <span style={{ fontSize:10, color:'#F59E0B' }}>⚠ לא זמין במכשיר זה</span>}
                    </div>
                  </div>
                  <div style={{ display:'flex', gap:6, flexShrink:0 }}>
                    {hasData && <button type="button" onClick={() => openDoc(d.id, d.mimeType, d.name)}
                      style={{ background:'#EFF6FF', border:'1px solid #BFDBFE', color:'#1D4ED8', borderRadius:8, padding:'6px 10px', fontWeight:700, cursor:'pointer', fontSize:12 }}>פתח</button>}
                    <button type="button" onClick={() => deleteDoc(d.id)}
                      style={{ background:'#FEF2F2', border:'1px solid #FECACA', color:'#DC2626', borderRadius:8, padding:'6px 10px', fontWeight:700, cursor:'pointer', fontSize:12 }}>✕</button>
                  </div>
                </div>
              )
            })}
          </div>
        )}
      </div>
    )
  }

  /* ── Global document browser ── */
  const renderDocsView = () => {
    const q = docSearchQuery.toLowerCase()
    const filtered = docs.filter(d => {
      if (q && !d.name.toLowerCase().includes(q) &&
          !DOC_TYPE_LABEL[d.type].includes(q) &&
          !(properties.find(p=>p.id===d.propertyId)?.name||'').toLowerCase().includes(q) &&
          !(tenants.find(t=>t.id===tenancies.find(tn=>tn.id===d.tenancyId)?.tenantId)?.name||'').toLowerCase().includes(q)
      ) return false
      return true
    }).sort((a,b) => b.date.localeCompare(a.date))

    return (
      <div style={{ display:'flex', flexDirection:'column', height:'100dvh', background:'#F9FAFB' }}>
        <div style={HDR}>
          <button style={BACK} onClick={() => setPropView('list')}>‹</button>
          <span style={{ fontWeight:700, fontSize:17, flex:1 }}>📄 כל המסמכים</span>
          <span style={{ fontSize:12, color:'#9CA3AF' }}>{docs.length} מסמכים</span>
        </div>

        {/* Search + filter */}
        <div style={{ padding:'10px 16px', background:'white', borderBottom:'1px solid #E5E7EB', flexShrink:0 }}>
          <input style={{ ...INP, marginBottom:8 }} placeholder="חיפוש לפי שם, נכס, שוכר..." value={docSearchQuery}
            onChange={e => setDocSearchQuery(e.target.value)} />
          <div style={{ display:'flex', gap:6 }}>
            {(['all','contract','renewal','receipt','other'] as const).map(t => {
              const isAll = t==='all'
              const active = isAll ? q==='' && docSearchQuery==='' : false
              return (
                <button key={t} type="button" onClick={() => setDocSearchQuery(isAll ? '' : DOC_TYPE_LABEL[t as TenancyDoc['type']])}
                  style={{ flex:1, padding:'5px 4px', borderRadius:8, border:`1.5px solid ${active?'#6366F1':'#E5E7EB'}`, background:active?'#EEF2FF':'white', fontSize:11, fontWeight:700, color:active?'#6366F1':'#6B7280', cursor:'pointer' }}>
                  {isAll ? 'הכל' : DOC_TYPE_LABEL[t as TenancyDoc['type']]}
                </button>
              )
            })}
          </div>
        </div>

        <div style={SCROLL}>
          {filtered.length === 0 ? (
            <div style={{ textAlign:'center', padding:'60px 20px', color:'#9CA3AF' }}>
              <div style={{ fontSize:48, marginBottom:12 }}>📄</div>
              <div style={{ fontWeight:700, fontSize:15, color:'#374151' }}>{docs.length===0 ? 'אין מסמכים עדיין' : 'לא נמצאו תוצאות'}</div>
            </div>
          ) : filtered.map(d => {
            const prop   = properties.find(p=>p.id===d.propertyId)
            const tncy   = tenancies.find(t=>t.id===d.tenancyId)
            const tenant = tncy ? tenants.find(t=>t.id===tncy.tenantId) : null
            const hasData = !!localStorage.getItem(lsKey(`doc_data_${d.id}`))
            return (
              <div key={d.id} style={{ background:'white', borderRadius:14, padding:'12px 14px', marginBottom:10, border:'1px solid #E5E7EB' }}>
                <div style={{ display:'flex', alignItems:'flex-start', gap:10 }}>
                  <span style={{ fontSize:24, flexShrink:0 }}>{DOC_TYPE_ICON[d.type]}</span>
                  <div style={{ flex:1, minWidth:0 }}>
                    <div style={{ fontWeight:700, fontSize:14, color:'#111827', marginBottom:2 }}>{d.name}</div>
                    <div style={{ display:'flex', gap:6, alignItems:'center', flexWrap:'wrap', marginBottom:4 }}>
                      <span style={{ fontSize:11, background:DOC_TYPE_COLOR[d.type]+'20', color:DOC_TYPE_COLOR[d.type], borderRadius:10, padding:'1px 7px', fontWeight:700 }}>{DOC_TYPE_LABEL[d.type]}</span>
                      <span style={{ fontSize:11, color:'#6B7280' }}>{d.date} · {fmtFileSize(d.size)}</span>
                    </div>
                    <div style={{ fontSize:12, color:'#6B7280' }}>
                      🏠 {prop?.name || '—'}
                      {tenant && <span> · 👤 {tenant.name}</span>}
                      {tncy && <span style={{ fontSize:11, color:'#9CA3AF' }}> · {tncy.contractStart.slice(0,7)} → {tncy.contractEnd.slice(0,7)}</span>}
                    </div>
                    {!hasData && <div style={{ fontSize:11, color:'#F59E0B', marginTop:4 }}>⚠ קובץ לא זמין במכשיר זה</div>}
                  </div>
                </div>
                <div style={{ display:'flex', gap:8, marginTop:10 }}>
                  {hasData && <button type="button" onClick={() => openDoc(d.id, d.mimeType, d.name)}
                    style={{ flex:1, background:'#EFF6FF', border:'1px solid #BFDBFE', color:'#1D4ED8', borderRadius:8, padding:'8px', fontWeight:700, cursor:'pointer', fontSize:13 }}>📂 פתח</button>}
                  <button type="button" onClick={() => { setSelPropId(d.propertyId); setSelViewTenancyId(d.tenancyId); setPropView('detail') }}
                    style={{ flex:1, background:'#F9FAFB', border:'1px solid #E5E7EB', color:'#374151', borderRadius:8, padding:'8px', fontWeight:700, cursor:'pointer', fontSize:13 }}>→ לנכס</button>
                  <button type="button" onClick={() => deleteDoc(d.id)}
                    style={{ background:'#FEF2F2', border:'1px solid #FECACA', color:'#DC2626', borderRadius:8, padding:'8px 12px', fontWeight:700, cursor:'pointer', fontSize:13 }}>✕</button>
                </div>
              </div>
            )
          })}
        </div>
      </div>
    )
  }

  const renderPropertiesTab = () => {
    if (propView==='editProp')    return renderEditProp()
    if (propView==='editTenancy') return renderEditTenancy()
    if (propView==='addTenant')   return renderAddTenantInline()
    if (propView==='detail')      return renderPropDetail()
    if (propView==='docs')        return renderDocsView()
    return renderPropList()
  }

  /* ════════════════════════════════════════
     TAB 2 — TENANTS
  ════════════════════════════════════════ */
  const renderTenantsTab = () => {
    if (tenantView==='edit') return (
      <div style={{ display:'flex', flexDirection:'column', height:'100dvh', background:'#F9FAFB' }}>
        <div style={HDR}>
          <button style={BACK} onClick={() => setTenantView('list')}>‹</button>
          <span style={{ fontWeight:700, fontSize:17, flex:1 }}>{tenantFormId ? 'עריכת שוכר' : 'שוכר חדש'}</span>
          <button style={BTN_P} onClick={() => {
            if (!tenantForm.name.trim()) return
            if (tenantFormId) setTenants(prev=>prev.map(t=>t.id===tenantFormId?{...tenantForm,id:tenantFormId}:t))
            else setTenants(prev=>[...prev,{...tenantForm,id:Date.now().toString()}])
            setTenantView('list'); showToast('✓ נשמר')
          }}>שמור</button>
        </div>
        <div style={SCROLL}>
          {([{f:'name',l:'שם מלא',t:'text'},{f:'phone',l:'טלפון',t:'tel'},{f:'email',l:'דוא"ל',t:'email'}] as const).map(({f,l,t}) => (
            <label key={f} style={{ display:'block', marginBottom:12 }}>
              <span style={LBL}>{l}</span>
              <input style={INP} type={t} value={(tenantForm as any)[f]} onChange={e=>setTenantForm(p=>({...p,[f]:e.target.value}))} />
            </label>
          ))}
          <label style={{ display:'block', marginBottom:12 }}>
            <span style={LBL}>סטטוס</span>
            <select style={INP} value={tenantForm.status} onChange={e=>setTenantForm(p=>({...p,status:e.target.value as any}))}>
              <option value="lead">{t('statusLead')}</option>
              <option value="active">{t('statusActiveTenant')}</option>
              <option value="past">{t('statusPastTenant')}</option>
            </select>
          </label>
          {tenantForm.status==='lead' && (
            <label style={{ display:'block', marginBottom:12 }}>
              <span style={LBL}>{t('interestedInProperty')}</span>
              <select style={INP} value={tenantForm.interestedPropertyId||''} onChange={e=>setTenantForm(p=>({...p,interestedPropertyId:e.target.value||null}))}>
                <option value="">בחר נכס...</option>
                {properties.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}
              </select>
            </label>
          )}
          <label style={{ display:'block', marginBottom:12 }}>
            <span style={LBL}>הערות</span>
            <textarea style={{...INP,resize:'none'}} value={tenantForm.notes} onChange={e=>setTenantForm(p=>({...p,notes:e.target.value}))} rows={3}/>
          </label>
          {tenantFormId && (
            <button type="button" onClick={()=>{setTenants(p=>p.filter(t=>t.id!==tenantFormId));setTenantView('list');showToast('נמחק')}}
              style={{ width:'100%', padding:12, background:'#FEF2F2', border:'1px solid #FECACA', borderRadius:10, color:'#DC2626', fontWeight:600, cursor:'pointer' }}>
              🗑 מחק שוכר
            </button>
          )}
        </div>
      </div>
    )

    const STATUS_LABELS: Record<Tenant['status'],string> = { lead:'מתעניינים', active:'שוכרים פעילים', past:'לשעבר' }
    const STATUS_COLORS: Record<Tenant['status'],string> = { lead:'#F59E0B', active:'#22C55E', past:'#9CA3AF' }
    return (
      <>
        <div style={HDR}>
          <button style={{ background:'none', border:'none', cursor:'pointer', padding:'0 4px', display:'flex', alignItems:'center', height:32 }} onClick={goToPmMain}>
            <img src="/Trn color.png" alt="חזור" style={{ height:22 }} />
          </button>
          <span style={{ fontWeight:700, fontSize:17, flex:1 }}>👤 {t('tabTenants')}</span>
          <button style={BTN_P} onClick={() => {
            setTenantFormId(null); setTenantForm({name:'',phone:'',email:'',extraPhones:[],notes:'',status:'lead',interestedPropertyId:null}); setTenantView('edit')
          }}>+ שוכר</button>
        </div>
        <div style={SCROLL}>
          {tenants.length===0 ? (
            <div style={{ textAlign:'center', padding:'60px 20px', color:'#9CA3AF' }}>
              <div style={{ fontSize:48, marginBottom:12 }}>👤</div>
              <div style={{ fontWeight:700, fontSize:16, color:'#374151' }}>{t('noTenantsYet')}</div>
            </div>
          ) : (['lead','active','past'] as Tenant['status'][]).map(status => {
            const group = tenants.filter(t=>t.status===status)
            if (group.length===0) return null
            return (
              <div key={status} style={{ marginBottom:16 }}>
                <div style={{ fontSize:12, fontWeight:700, color:STATUS_COLORS[status], marginBottom:8, padding:'0 4px' }}>
                  {STATUS_LABELS[status]} ({group.length})
                </div>
                {group.map(t => {
                  const intProp = t.interestedPropertyId ? properties.find(p=>p.id===t.interestedPropertyId) : null
                  const activeTn = tenancies.find(tn=>tn.tenantId===t.id&&tn.isCurrent)
                  const activeProp = activeTn ? properties.find(p=>p.id===activeTn.propertyId) : null
                  return (
                    <div key={t.id} style={CARD}>
                      <div style={{ display:'flex', justifyContent:'space-between', alignItems:'flex-start', marginBottom:6 }}>
                        <div style={{ flex:1 }}>
                          <div style={{ fontWeight:700, fontSize:15, color:'#111827' }}>{t.name}</div>
                          {t.phone && <div style={{ fontSize:13, color:'#6B7280' }}>📞 {t.phone}</div>}
                          {t.email && <div style={{ fontSize:13, color:'#6B7280' }}>✉ {t.email}</div>}
                          {intProp && <div style={{ fontSize:12, color:'#F59E0B', fontWeight:600, marginTop:4 }}>🔍 {t('interestedIn')}: {intProp.name}</div>}
                          {activeProp && <div style={{ fontSize:12, color:'#22C55E', fontWeight:600, marginTop:4 }}>🏠 {(tt[lang].tenantAt as (n:string,d:string)=>string)(activeProp.name, activeTn?.contractEnd||'')}</div>}
                          {t.notes && <div style={{ fontSize:12, color:'#9CA3AF', marginTop:4 }}>📝 {t.notes}</div>}
                        </div>
                        <button type="button" onClick={() => { setTenantFormId(t.id); setTenantForm({name:t.name,phone:t.phone,email:t.email,extraPhones:t.extraPhones,notes:t.notes,status:t.status,interestedPropertyId:t.interestedPropertyId}); setTenantView('edit') }}
                          style={{ background:'#F3F4F6', border:'none', borderRadius:8, padding:'4px 10px', fontWeight:600, cursor:'pointer', fontSize:12, color:'#374151', flexShrink:0, marginRight:8 }}>ערוך</button>
                      </div>
                      {t.phone && (
                        <div style={{ display:'flex', gap:8, marginTop:8 }}>
                          <button type="button" onClick={()=>sendWA(t.phone,`שלום ${t.name}, `)} style={{ flex:1, padding:'7px', background:'#F0FDF4', border:'1px solid #BBF7D0', borderRadius:8, color:'#15803D', fontWeight:600, cursor:'pointer', fontSize:12 }}>💬 WhatsApp</button>
                          <button type="button" onClick={()=>{window.location.href=`tel:${t.phone}`}} style={{ flex:1, padding:'7px', background:'#F9FAFB', border:'1px solid #E5E7EB', borderRadius:8, color:'#374151', fontWeight:600, cursor:'pointer', fontSize:12 }}>📞 {t('callAction')}</button>
                          {t.email && <button type="button" onClick={()=>{window.location.href=`mailto:${t.email}`}} style={{ flex:1, padding:'7px', background:'#EFF6FF', border:'1px solid #BFDBFE', borderRadius:8, color:'#1D4ED8', fontWeight:600, cursor:'pointer', fontSize:12 }}>✉ {t('emailAction')}</button>}
                        </div>
                      )}
                    </div>
                  )
                })}
              </div>
            )
          })}
        </div>
      </>
    )
  }
  /* ════════════════════════════════════════
     TAB 3 — TASKS
  ════════════════════════════════════════ */
  const renderTasksTab = () => {
    const open = tasks.filter(t=>!t.done)
    const done = tasks.filter(t=>t.done)
    const urgency = (t: PMTask) => {
      const d = daysBetween(todayStr(), t.dueDate)
      if (d<=7) return 0; if (d<=30) return 1; return 2
    }
    const ICONS: Record<string,string> = { renewal:'🔄', deposit:'💰', checks:'📑', custom:'📌' }
    const GROUPS = [
      { label:t('urgentThisWeek'),   filter:(t:PMTask)=>urgency(t)===0 },
      { label:t('soonThisMonth'), filter:(t:PMTask)=>urgency(t)===1 },
      { label:t('laterLabel'),         filter:(t:PMTask)=>urgency(t)===2 },
    ]
    return (
      <>
        <div style={HDR}>
          <button style={{ background:'none', border:'none', cursor:'pointer', padding:'0 4px', display:'flex', alignItems:'center', height:32 }} onClick={goToPmMain}>
            <img src="/Trn color.png" alt="חזור" style={{ height:22 }} />
          </button>
          <span style={{ fontWeight:700, fontSize:17, flex:1 }}>✅ {t('tabTasks')}</span>
          {open.length>0 && <span style={{ background:'#EF4444', color:'white', borderRadius:20, padding:'2px 10px', fontSize:12, fontWeight:700, marginLeft:4 }}>{open.length}</span>}
          <button style={BTN_P} onClick={() => {
            const title = prompt('כותרת המשימה')
            if (!title) return
            setTasks(prev=>[...prev,{id:Date.now().toString(),propertyId:'',tenantId:'',tenancyId:'',type:'custom',title,dueDate:todayStr(),done:false,doneAt:'',autoGenerated:false}])
          }}>{t('addTask')}</button>
        </div>
        <div style={SCROLL}>
          {open.length===0 && (
            <div style={{ textAlign:'center', padding:'60px 20px', color:'#9CA3AF' }}>
              <div style={{ fontSize:48 }}>✅</div>
              <div style={{ fontWeight:700, fontSize:16, color:'#374151', marginTop:12 }}>{t('noOpenTasks')}</div>
            </div>
          )}
          {GROUPS.map(g => {
            const group = open.filter(g.filter)
            if (group.length===0) return null
            return (
              <div key={g.label} style={{ marginBottom:16 }}>
                <div style={{ fontSize:13, fontWeight:700, color:'#374151', marginBottom:8 }}>{g.label}</div>
                {group.map(t => {
                  const tn = t.tenantId ? tenants.find(x=>x.id===t.tenantId) : null
                  return (
                    <div key={t.id} style={{ ...CARD, display:'flex', alignItems:'flex-start', gap:10, padding:'12px 14px' }}>
                      <button type="button" onClick={() => setTasks(prev=>prev.map(x=>x.id===t.id?{...x,done:true,doneAt:todayStr()}:x))}
                        style={{ width:24, height:24, borderRadius:'50%', border:'2px solid #D1D5DB', background:'white', cursor:'pointer', flexShrink:0, marginTop:2, fontSize:13, display:'flex', alignItems:'center', justifyContent:'center' }}>☐</button>
                      <div style={{ flex:1 }}>
                        <div style={{ fontWeight:700, fontSize:14 }}>{ICONS[t.type]} {t.title}</div>
                        {t.propertyId && <div style={{ fontSize:12, color:'#6B7280', marginTop:2 }}>🏠 {getPropName(t.propertyId)}{t.tenantId ? ` — ${getTenantName(t.tenantId)}` : ''}</div>}
                        <div style={{ fontSize:11, color:'#9CA3AF', marginTop:2 }}>{t('untilLabel')} {t.dueDate}</div>
                      </div>
                      {tn?.phone && (
                        <button type="button" onClick={() => {
                          const msgs: Record<string,string> = {
                            renewal:`שלום ${tn.name}, תזכורת לחידוש חוזה עבור ${getPropName(t.propertyId)}. 🙏`,
                            deposit:`שלום ${tn.name}, תזכורת להעברת פיקדון עבור ${getPropName(t.propertyId)}. 🙏`,
                            checks:`שלום ${tn.name}, תזכורת לשלוח צ'קים עבור ${getPropName(t.propertyId)}. 🙏`,
                            custom:`שלום ${tn.name}, ${t.title}`,
                          }
                          sendWA(tn.phone, msgs[t.type] || msgs.custom)
                        }} style={{ padding:'6px 10px', background:'#F0FDF4', border:'1px solid #BBF7D0', borderRadius:8, color:'#15803D', fontWeight:600, cursor:'pointer', fontSize:11, flexShrink:0 }}>{t('sendAction')}</button>
                      )}
                    </div>
                  )
                })}
              </div>
            )
          })}
          {done.length>0 && (
            <div style={{ marginBottom:16 }}>
              <div style={{ fontSize:13, fontWeight:700, color:'#9CA3AF', marginBottom:8 }}>{(tt[lang].completedCount as (n:number)=>string)(done.length)}</div>
              {done.slice(0,5).map(t => (
                <div key={t.id} style={{ ...CARD, display:'flex', alignItems:'center', gap:10, padding:'10px 14px', opacity:0.6 }}>
                  <span style={{ fontSize:18 }}>✅</span>
                  <div style={{ flex:1 }}>
                    <div style={{ fontWeight:600, fontSize:13, textDecoration:'line-through' }}>{t.title}</div>
                    <div style={{ fontSize:11, color:'#9CA3AF' }}>{getPropName(t.propertyId)}</div>
                  </div>
                  <button type="button" onClick={()=>setTasks(prev=>prev.map(x=>x.id===t.id?{...x,done:false,doneAt:''}:x))}
                    style={{ background:'none', border:'1px solid #E5E7EB', borderRadius:8, padding:'4px 8px', cursor:'pointer', fontSize:11, color:'#6B7280' }}>{t('undoAction')}</button>
                </div>
              ))}
            </div>
          )}
        </div>
      </>
    )
  }

  /* ════════════════════════════════════════
     TAB 4 — DASHBOARD
  ════════════════════════════════════════ */
  const renderDashboard = () => {
    const totalMonthly = properties.reduce((s,p)=>s+p.monthlyRent,0)
    const rented = tenancies.filter(t=>t.isCurrent)
    const vacant = properties.filter(p=>!rented.find(t=>t.propertyId===p.id))
    const ganttMonths: string[] = []
    const now = new Date()
    for (let i=-2; i<26; i++) {
      const d = new Date(now.getFullYear(), now.getMonth()+i, 1)
      ganttMonths.push(`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`)
    }
    const cm = currYM()
    return (
      <>
        <div style={HDR}>
          <button style={{ background:'none', border:'none', cursor:'pointer', padding:'0 4px', display:'flex', alignItems:'center', height:32 }} onClick={goToPmMain}>
            <img src="/Trn color.png" alt="חזור" style={{ height:22 }} />
          </button>
          <span style={{ fontWeight:700, fontSize:17, flex:1 }}>📊 {t('tabDashboard')}</span>
        </div>
        <div style={SCROLL}>
          {/* KPI cards */}
          <div style={{ display:'grid', gridTemplateColumns:'1fr 1fr 1fr', gap:10, marginBottom:16 }}>
            {[
              { label: t('monthlyRentKpi'), val:fmtMoney(totalMonthly), color:'#22C55E' },
              { label: t('annualRentKpi'),  val:fmtMoney(totalMonthly*12), color:'#6366F1' },
              { label: t('vacantProperties'), val:String(vacant.length), color:vacant.length>0?'#EF4444':'#22C55E' },
            ].map(({label,val,color}) => (
              <div key={label} style={{ background:'white', borderRadius:12, padding:'12px 10px', border:'1px solid #E5E7EB', textAlign:'center' }}>
                <div style={{ fontSize:16, fontWeight:700, color }}>{val}</div>
                <div style={{ fontSize:10, color:'#9CA3AF', marginTop:2 }}>{label}</div>
              </div>
            ))}
          </div>

          {/* Per-property income */}
          <div style={CARD}>
            <div style={{ fontWeight:700, fontSize:14, marginBottom:12 }}>💰 {t('incomeByProperty')}</div>
            {properties.map(p => {
              const ct = rented.find(t=>t.propertyId===p.id)
              const ctn = ct ? tenants.find(t=>t.id===ct.tenantId) : null
              const days = ct?.contractEnd ? daysLeft(ct.contractEnd) : null
              const dc = days===null?'#9CA3AF':days<0?'#EF4444':days<=60?'#F59E0B':'#22C55E'
              return (
                <div key={p.id} style={{ display:'flex', justifyContent:'space-between', alignItems:'center', padding:'10px 0', borderBottom:'1px solid #F3F4F6' }}>
                  <div>
                    <div style={{ fontWeight:600, fontSize:14 }}>{p.name}</div>
                    <div style={{ fontSize:12, color:ctn?'#6B7280':'#EF4444' }}>{ctn ? ctn.name : t('vacant')}</div>
                  </div>
                  <div style={{ textAlign:'left' }}>
                    <div style={{ fontWeight:700, fontSize:15, color:ctn?'#22C55E':'#EF4444' }}>{ctn ? fmtMoney(p.monthlyRent) : '₪0'}</div>
                    {days!==null && <div style={{ fontSize:11, color:dc }}>{days<0?t('expired'):(tt[lang].daysToEnd as (n:number)=>string)(days)}</div>}
                  </div>
                </div>
              )
            })}
          </div>

          {/* Gantt */}
          <div style={CARD}>
            <div style={{ fontWeight:700, fontSize:14, marginBottom:12 }}>📅 {t('availabilityCalendar')}</div>
            <div style={{ overflowX:'auto' }}>
              <table style={{ borderCollapse:'collapse', minWidth:'100%', fontSize:11 }}>
                <thead>
                  <tr>
                    <th style={{ textAlign:'right', padding:'4px 8px', color:'#6B7280', minWidth:70 }}>{t('propertyCol')}</th>
                    {ganttMonths.map(m => (
                      <th key={m} style={{ padding:'4px 3px', color:m===cm?'#6366F1':'#9CA3AF', fontWeight:m===cm?700:400, minWidth:34, textAlign:'center', borderRight:'1px solid #F3F4F6', verticalAlign:'bottom' }}>
                        {m.slice(5)==='01' && <div style={{ fontSize:8, color:'#6366F1', fontWeight:800, lineHeight:1.2 }}>{m.slice(0,4)}</div>}
                        {m.slice(5)}
                      </th>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  {properties.map(p => {
                    const propTen = tenancies.filter(t=>t.propertyId===p.id)
                    return (
                      <tr key={p.id} style={{ borderTop:'1px solid #F3F4F6' }}>
                        <td style={{ padding:'6px 8px', fontWeight:600, color:'#374151', fontSize:12 }}>{p.name}</td>
                        {ganttMonths.map(m => {
                          const tn = propTen.find(t => t.contractStart.slice(0,7)<=m && t.contractEnd.slice(0,7)>=m)
                          const st2 = tn ? getTenancyStatus(tn) : null
                          const bg = tn ? (st2==='active'?'#22C55E':st2==='future'?'#A78BFA':'#9CA3AF') : '#FEE2E2'
                          const isEnd = tn && tn.contractEnd.slice(0,7)===m
                          return (
                            <td key={m} style={{ padding:'6px 3px', background:bg, textAlign:'center', borderRight:'1px solid #F9FAFB', fontSize:9, color:'white', fontWeight:700 }}>
                              {isEnd ? '⚠' : ''}
                            </td>
                          )
                        })}
                      </tr>
                    )
                  })}
                </tbody>
              </table>
              <div style={{ display:'flex', gap:12, marginTop:8, fontSize:11, color:'#6B7280', flexWrap:'wrap' }}>
                <span><span style={{ display:'inline-block', width:12, height:10, background:'#22C55E', borderRadius:2, marginLeft:4 }}/>{t('legendActiveRented')}</span>
                <span><span style={{ display:'inline-block', width:12, height:10, background:'#A78BFA', borderRadius:2, marginLeft:4 }}/>{t('legendFuture')}</span>
                <span><span style={{ display:'inline-block', width:12, height:10, background:'#9CA3AF', borderRadius:2, marginLeft:4 }}/>{t('legendPast')}</span>
                <span><span style={{ display:'inline-block', width:12, height:10, background:'#FEE2E2', border:'1px solid #FECACA', borderRadius:2, marginLeft:4 }}/>{t('vacant')}</span>
                <span>⚠ {t('legendEnding')}</span>
              </div>
            </div>
          </div>
        </div>
      </>
    )
  }

  /* ════════════════════════════════════════
     MAIN RENDER
  ════════════════════════════════════════ */
  const TABS = [
    { id:'properties' as Tab, label: t('tabProperties'), icon:'🏠' },
    { id:'tenants'    as Tab, label: t('tabTenants'),    icon:'👤' },
    { id:'tasks'      as Tab, label: t('tabTasks'),      icon:'✅' },
    { id:'dashboard'  as Tab, label: t('tabDashboard'),  icon:'📊' },
  ]
  const openTaskCount = tasks.filter(t=>!t.done).length

  // Full-screen sub-views that take over the whole screen (no tab bar)
  const isFullScreen =
    (tab==='properties' && ['editProp','editTenancy','addTenant'].includes(propView)) ||
    (tab==='tenants' && tenantView==='edit')

  const subView = isFullScreen ? (
    tab==='properties' ? renderPropertiesTab() : renderTenantsTab()
  ) : null

  if (isFullScreen) return (
    <>
      {subView}
      {toast && (
        <div style={{ position:'fixed', bottom:20, left:'50%', transform:'translateX(-50%)', background:'#1F2937', color:'white', padding:'10px 20px', borderRadius:20, fontWeight:600, zIndex:200, whiteSpace:'nowrap' }}>
          {toast}
        </div>
      )}
    </>
  )

  return (
    <div style={{ display:'flex', flexDirection:'column', height:'100dvh', background:'#F9FAFB' }}>
      <div style={{ flex:1, overflowY:'auto', display:'flex', flexDirection:'column', minHeight:0 }}>
        {tab==='properties' && renderPropertiesTab()}
        {tab==='tenants'    && renderTenantsTab()}
        {tab==='tasks'      && renderTasksTab()}
        {tab==='dashboard'  && renderDashboard()}
      </div>

      {/* Tab bar */}
      <div style={{ background:'white', borderTop:'1px solid #E5E7EB', display:'flex', flexShrink:0 }}>
        {TABS.map(({id,label,icon}) => (
          <button key={id} type="button"
            onClick={() => { setTab(id); if(id==='properties') setPropView('list'); if(id==='tenants') setTenantView('list') }}
            style={{ flex:1, padding:'10px 4px 12px', background:'none', border:'none', cursor:'pointer',
              display:'flex', flexDirection:'column', alignItems:'center', gap:3,
              color:tab===id ? '#6366F1' : '#9CA3AF',
              fontWeight:tab===id ? 700 : 500, fontSize:10,
              borderTop:tab===id ? '2px solid #6366F1' : '2px solid transparent',
              position:'relative' }}>
            <span style={{ fontSize:18 }}>{icon}</span>
            <span>{label}</span>
            {id==='tasks' && openTaskCount>0 && (
              <span style={{ position:'absolute', top:4, right:'18%', background:'#EF4444', color:'white', borderRadius:10, padding:'1px 5px', fontSize:9, fontWeight:700 }}>
                {openTaskCount}
              </span>
            )}
          </button>
        ))}
      </div>

      {toast && (
        <div style={{ position:'fixed', bottom:80, left:'50%', transform:'translateX(-50%)', background:'#1F2937', color:'white', padding:'10px 20px', borderRadius:20, fontWeight:600, zIndex:200, whiteSpace:'nowrap' }}>
          {toast}
        </div>
      )}
    </div>
  )
}
